#| ---
#| title: Compile initial litter data for the SAFE scenario
#|
#| description: |
#|     This R script compiles initial litter data for the SAFE scenario
#|     from various data analyses into a single netCDF file.
#|     See the metadata in data/scenarios/safe/soil_litter_metadata.toml
#|     for specific file paths that analysed each variable.
#|
#| virtual_ecosystem_module: Litter
#|
#| author: Hao Ran Lai
#|
#| status: final
#|
#| input_files:
#|   - name: soil_litter_metadata.toml
#|     path: data/scenarios/safe
#|     description: |
#|         Metadata for soil and litter data analyses, currently including
#|         file paths and units
#|   - name: safe_grid_definition.toml
#|     path: data/derived/site/safe/
#|     description: |
#|         Metadata for SAFE grids, primarily to define the data generation
#|         area
#|   - name: litter_stock.csv
#|     path: data/derived/litter/stock
#|     description: |
#|         Estimated litter stock (aboveground/belowground metabolic and
#|         structural, and woody), generated by
#|         analysis/litter/stock/combine_stocks.R
#|
#| output_files:
#|   - name: litter_safe.nc
#|     path: data/scenarios/safe/safe_1/data
#|     description: |
#|         Litter input data for the SAFE scenario meant for ve_run.
#|
#| source_files:
#|   - name: convert_df_to_nc.R
#|     path: tools/R/
#|     description: |
#|         Function to convert input dataframe to netCDF
#|   - name: initial_nutrient_aboveground.R
#|     path: analysis/litter/nutrient_pool/
#|     description: |
#|         Code to estimate aboveground litter nutrient ratios and lignin
#|   - name: initial_nutrient_belowground.R
#|     path: analysis/litter/nutrient_pool/
#|     description: |
#|         Code to estimate belowground litter nutrient ratios and lignin
#|   - name: initial_nutrient_woody.R
#|     path: analysis/litter/nutrient_pool/
#|     description: |
#|         Code to estimate woody litter nutrient ratios and lignin
#|
#| package_dependencies:
#|     - tidyverse
#|     - mvtnorm
#|     - RcppTOML
#|     - readxl
#|     - glmmTMB
#|     - RNetCDF
#|     - reshape2
#|
#| usage_notes: |
#|     For more details on statistical and data assumptions, see
#|     data/scenarios/safe/soil_metadata.toml
#| ---

library(tidyverse)
library(mvtnorm)
library(RcppTOML)
library(readxl)
library(glmmTMB)
library(RNetCDF)
source("tools/R/convert_df_to_nc.R")

set.seed(20260713)


# Litter metadata ---------------------------------------------------------

litter_meta <- parseTOML("data/scenarios/safe/soil_litter_metadata.toml")
litter_meta <- litter_meta$litter


# SAFE site metadata ----------------------------------------------------

safe <-
  parseTOML("data/derived/site/safe/safe_grid_definition.toml") |>
  pluck("Scenario", "safe_1")

# total number of grids
n_sim <- with(safe, cell_nx * cell_ny)


# Set up dataframe --------------------------------------------------------
# this dataframe will store generated initial values, and then be converted
# to a netCDF output at the end

dat <-
  expand_grid(
    cell_x = safe$cell_x_centres,
    cell_y = safe$cell_y_centres
  )


# Litter carbon stock -----------------------------------------------------

# This section is about the "C" part in:
# litter_pool_above_metabolic_cnp
# litter_pool_above_structural_cnp
# litter_pool_woody_cnp
# litter_pool_below_metabolic_cnp
# litter_pool_below_structural_cnp

# Litter stock means are straightforward, but not their variances. This is
# because we modelled physical litter types (e.g., leaf, root, twig) but then
# converted them to more abstract pools (e.g., metabolic and structural).
# During this conversion, the propagation of mean values is straightforward,
# but not the propagation of variances is less so. For example, we may know
# that the mean of a structural pool is (1 - f_m) * X, but what is its
# variance? There are a few statistical approaches (e.g., delta method and
# numerical simulation) but they are either slightly out of my comfort zone or
# time consuming. So I opted to set standard deviations at 1/10 of their mean.
# This value is selected such that the aboveground pool sum has similar range
# to their observed physical counterparts at SAFE. Then I assume the same also
# applies to the woody and belowground pools.

litter_stocks_c <-
  read_csv("data/derived/litter/stock/litter_stock.csv") |>
  # extract logged forest values for SAFE
  filter(Logging_grp == "Logged")

# retrieve stock means and then calculate SDs
# they are in log scales to generate stocks with a lognormal distribution
# to keep them positively bound
litter_stocks_c_meanlog <- log(litter_stocks_c$stock)
litter_stocks_c_sdlog <- abs(litter_stocks_c_meanlog / 10)

# simulate litter stocks
litter_stocks_c_sim <- mapply(
  function(mean, sd) rlnorm(n_sim, mean, sd),
  mean = litter_stocks_c_meanlog,
  sd = litter_stocks_c_sdlog
)
colnames(litter_stocks_c_sim) <- c(
  "litter_pool_above_metabolic_c",
  "litter_pool_above_structural_c",
  "litter_pool_below_metabolic_c",
  "litter_pool_below_structural_c",
  "litter_pool_woody_c"
)

# add to dataset
dat <- bind_cols(dat, litter_stocks_c_sim)


# Litter N and P stocks ---------------------------------------------------

# First, aboveground litter including:
# lignin_above_structural
# And the "N" and "P" parts of:
# litter_pool_above_metabolic_cnp
# litter_pool_above_structural_cnp

# source models for prediction
source("analysis/litter/nutrient_pool/initial_nutrient_aboveground.R")

# find the row index of a SAFE sample site (litter_type == "S")
# any row works as they share the same fixed effects; take the first
litter_above_safe_idx <- which(litter$litter_type == "S")[[1]]

# predictions, added directly to the dataset
dat <-
  dat |>
  mutate(
    c_n_ratio_above_metabolic = as.numeric(simulate(
      mod_C.N_met_above,
      nsim = n_sim
    )[litter_above_safe_idx, ]),
    c_n_ratio_above_structural = r_century * c_n_ratio_above_metabolic,
    c_p_ratio_above_metabolic = as.numeric(simulate(
      mod_C.P_met_above,
      nsim = n_sim
    )[litter_above_safe_idx, ]),
    c_p_ratio_above_structural = r_century * c_p_ratio_above_metabolic,
    lignin_above_structural = as.numeric(simulate(
      mod_lignin_above,
      nsim = n_sim
    )[litter_above_safe_idx, ])
  ) |>
  # calculate litter N and P stocks from C stock and C:N & C:P ratios
  mutate(
    litter_pool_above_metabolic_n = litter_pool_above_metabolic_c /
      c_n_ratio_above_metabolic,
    litter_pool_above_structural_n = litter_pool_above_structural_c /
      c_n_ratio_above_structural,
    litter_pool_above_metabolic_p = litter_pool_above_metabolic_c /
      c_p_ratio_above_metabolic,
    litter_pool_above_structural_p = litter_pool_above_structural_c /
      c_p_ratio_above_structural
  )

# Second, belowground litter including:
# lignin_below_structural
# And the "N" and "P" parts of:
# litter_pool_below_metabolic_cnp
# litter_pool_below_structural_cnp

############ Fine root stoichiometry is from undisturbed forest ###############
# Worth discussing with Arne because the root nutrients were based on the
# same input data for Maliau

# Third, woody litter including:
# lignin_woody
# And the "N" and "P" parts of:
# litter_pool_woody_cnp

# source models for prediction
source("analysis/litter/nutrient_pool/initial_nutrient_woody.R")

# find the row index of a SAFE site, there will be three rows for P, N and C
# we will use the first site because it does not matter which site for the
# simulation purpose (they have the same fixed effects)
deadwood_safe_idx <- which(nutrient_deadwood$Logging_grp == "Logged")[1:3]

# simulate deadwood P, N and C
nutrient_deadwood_sim <-
  t(simulate(mod_nutrient_deadwood, nsim = n_sim)[deadwood_safe_idx, ])
colnames(nutrient_deadwood_sim) <- nutrient_deadwood$Type[deadwood_safe_idx]

# simulate deadwood lignin
lignin_sim <- abs(rnorm(n_sim, lignin_mean, lignin_sd))
# convert lignin from mass/mass to g C/g C
# the lignin C content = 62.5% comes from
# Martin et al. (2021) DOI: 10.1038/s41467-021-21149-9
lignin_sim <-
  lignin_sim * 0.625 / (nutrient_deadwood_sim[, "C_total"] / 100)

# add to the dataset
dat <-
  dat |>
  mutate(
    c_n_ratio_woody = nutrient_deadwood_sim[, "C_total"] /
      nutrient_deadwood_sim[, "N_total"],
    c_p_ratio_woody = nutrient_deadwood_sim[, "C_total"] /
      nutrient_deadwood_sim[, "P_total"],
    lignin_woody = lignin_sim
  ) |>
  # calculate litter N and P stocks from C stock and C:N & C:P ratios
  mutate(
    litter_pool_woody_n = litter_pool_woody_c / c_n_ratio_woody,
    litter_pool_woody_p = litter_pool_woody_c / c_p_ratio_woody
  )

# Combine litter C, N and P stocks into triplets
dat <-
  dat |>
  mutate(
    litter_pool_above_metabolic_cnp = pmap(
      list(
        litter_pool_above_metabolic_c,
        litter_pool_above_metabolic_n,
        litter_pool_above_metabolic_p
      ),
      c
    ),
    litter_pool_below_metabolic_cnp = pmap(
      list(
        litter_pool_below_metabolic_c,
        litter_pool_below_metabolic_n,
        litter_pool_below_metabolic_p
      ),
      c
    ),
    litter_pool_above_structural_cnp = pmap(
      list(
        litter_pool_above_structural_c,
        litter_pool_above_structural_n,
        litter_pool_above_structural_p
      ),
      c
    ),
    litter_pool_below_structural_cnp = pmap(
      list(
        litter_pool_below_structural_c,
        litter_pool_below_structural_n,
        litter_pool_below_structural_p
      ),
      c
    ),
    litter_pool_woody_cnp = pmap(
      list(
        litter_pool_woody_c,
        litter_pool_woody_n,
        litter_pool_woody_p
      ),
      c
    ),
    .keep = "unused"
  )


# Write data to netCDF ----------------------------------------------------

# collect litter metadata
litter_meta_df <-
  reshape2::melt(lapply(litter_meta, function(meta) meta$unit)) |>
  select(
    variable = L1,
    unit = value
  )

# convert data to netCDF
convert_df_to_nc(
  data = dat,
  filename = "data/scenarios/safe/safe_1/data/litter_safe.nc",
  x = safe$cell_x_centres,
  y = safe$cell_y_centres,
  element = c("C", "N", "P"),
  variables = litter_meta_df$variable,
  units = litter_meta_df$unit,
  description = "Litter data for the SAFE scenario"
)
