#| ---
#| title: Functions to build a validation database
#|
#| description: |
#|     Here we use a config-driven pipeline to read, wrangle, unit-convert, and
#|     combine multiple datasets into a single master file, hereafter referred to as
#|     the "validation database". We are not aiming for a full database backend, instead
#|     the main goal is to avoid having to write many custom codes that each only work
#|     for one dataset. The idea to run a single script to build the database, while YAML
#|     config metadata handles all dataset-specific idiosyncracies.
#|     Please refer to `docs/validation_database.md` for a full documentation.
#|
#| virtual_ecosystem_module: [Soil, Litter]
#|
#| author: Hao Ran Lai
#|
#| status: final
#|
#| input_files:
#|
#| output_files:
#|
#| package_dependencies:
#|     - arrow
#|     - cli
#|     - dplyr
#|     - purrr
#|     - rcrossref
#|     - readr
#|     - rlang
#|     - stats
#|     - tibble
#|     - tidyr
#|     - toml
#|     - utils
#|     - yaml
#|     - yesno
#|
#| usage_notes: |
#|   Please refer to `docs/validation_database.md` for a step-by-step tutorial.
#| ---

#' Log decision on whether a dataset should be included for validation purposes
#'
#' This function is intended to be used as \code{log_dataset()}, which will display
#' a UI in the R console and prompt you to enter the DOI and notes on
#' decisions. The log is then stored as a human-readable YAML file in the
#' specified output path, which defaults to the soil module for now.
#'
#' @param filename Filename of the source metadata, which currently defaults
#'   to the soil module
#'
#' @details
#' You will asked to enter:
#' \describe{
#'   \item{DOI}{DOI string of the dataset or publication}
#'   \item{Decision}{A menu to select decision}
#'   \item{Reason}{(Optional) A menu to select reason}
#'   \item{Notes}{(Optional) A string of long-form rationale}
#' }
#'
#' @returns A YAML file logging the decision and source metadata in
#'   \code{filename}.
#'
#' @export
#'
#' @examples
#' box::use(tools/R/valdb)
#' box::help(valdb$log_dataset)  # if you need a conventional R help page
#' valdb$log_dataset()

log_dataset <- function(
  filename = "data/derived/soil/validation/config/sources.yaml"
) {
  # prompt to enter DOI
  doi <- readline("Enter DOI: ")

  # read source yaml file if it already exists
  if (file.exists(filename)) {
    sources <- yaml::read_yaml(filename)
    # exit early if a DOI has already been logged
    doi_existing <- purrr::map_chr(sources, "doi")
    if (tolower(doi) %in% tolower(doi_existing)) {
      cli::cli_abort("{doi} has already been logged in {filename}.")
    }
  }

  # download dataset metadata
  meta <- rcrossref::cr_cn(doi, format = "bibentry")

  # prompt for decision, decision, decision...
  decision <- utils::select.list(
    c("included", "excluded"),
    title = "Decision (enter 0 to skip): ",
    graphics = FALSE
  )
  if (decision == "") {
    decision <- "skipped"
  }

  # prompt for short-form reason
  reason <- utils::select.list(
    c("used_elsewhere", "no_raw_data", "no_soil_data"),
    title = "Reason (enter 0 to skip): ",
    graphics = FALSE
  )

  # prompt for long-form notes
  notes <- readline("Notes (leave blank to skip): ")

  # Build new record
  new_record <- list(
    doi = meta$doi,
    decision = decision,
    reason = reason,
    notes = notes,
    logged_at = format(Sys.time(), "%Y-%m-%d"),
    metadata = list(
      title = meta$title,
      author = meta$author,
      year = meta$year,
      journal = as.character(meta$journal %||% NA),
      publisher = meta$publisher,
      url = meta$url,
      keywords = meta$keywords
    )
  )

  # append new record to existing source YAML if the latter already exists
  if (file.exists(filename)) {
    sources <- c(sources, list(new_record))
  } else {
    sources <- list(new_record)
  }

  # Write YAML
  yaml::write_yaml(sources, filename)

  # Completion message
  cli::cli_alert_info("Dataset from {doi} is {decision}")
  cli::cli_alert_success("Decision log saved to\n{filename}")
}


#' Add a template schema of dataset metadata and config
#'
#' @param source_yaml Filename of the dataset log YAML file. We expect this to
#'   have been generated by [log_dataset()].
#' @param
#'
#' @returns An edited YAML config file replacing the previous unedited version.
#'
#' @export
#' @examples
#' box::use(tools/R/valdb)
#' valdb$add_schema(
#'   "data/derived/soil/validation/config/sources.yaml",
#'   doi = ""
#' )

add_schema <- function(
  source_yaml = "data/derived/soil/validation/config/sources.yaml",
  doi = "10.5281/ZENODO.8158810"
) {
  # Read existing YAML
  sources <- yaml::read_yaml(source_yaml)

  # Find target data source by DOI
  doi_list <- purrr::map_chr(sources, "doi")
  target_id <- which(tolower(doi_list) == tolower(doi))

  # warn if source_id already exists, indicating that a schema has already been
  # added previously
  if ("source_id" %in% names(sources[[target_id]])) {
    if (
      !yesno::yesno(
        c(
          "`source_id` already exists in the source YAML metadata.\n",
          "Proceeding would overwrite the previous entries, are you sure?"
        )
      )
    ) {
      stop("Aborted.")
    }
  }

  # Default template schema
  template <- list(
    source_id = "author_year",
    data_file = "data/primary/soil/source_id/*.csv",
    skip_rows = 0L,
    variables = list(
      var_original_1 = list(
        var_canonical = "var_ve_1",
        unit = "unit",
        description = NA
      )
    ),
    dedup_key = c("sample_id", "date", "site_id")
  )

  # add the template entries to the target source YAML section
  sources[[target_id]] <- purrr::list_modify(sources[[target_id]], !!!template)

  # Write back
  yaml::write_yaml(sources, source_yaml)

  # Open the YAML file in the editor for editing
  utils::file.edit(source_yaml)
}


#' (Re)Build the validation database
#'
#' Build or rebuild the validation database based on the YAML configs of source
#' datasets.
#'
#' @param config_dir Path to where the dataset YAML config files are stored.
#' @param db_path Output path for the harmonised database.
#'
#' @returns A harmonised database stored in db_path. Currently it is written out
#'   in the parquet format for efficient compression (and possibly appending).
#'   We may consider a plain csv in the future.
#'
#' @export
#' @examples
#' box::use(tools/R/valdb)
#' valdb$build_validation_database()

build_validation_database <- function(
  config_dir = "data/derived/soil/validation/config",
  db_path = "data/derived/soil/validation/database"
) {
  # Configs ----------------------------------------------------------------

  # load unit conversions
  # the CSV file needs to be manually updated when there is a new unit_from and
  # unit_to pairs
  unit_conversions <-
    readr::read_csv(
      file.path(config_dir, "unit_conversions.csv"),
      show_col_types = FALSE
    ) |>
    # convert literal function to function objects
    dplyr::mutate(
      convert_unit = purrr::map(
        `function`,
        ~ rlang::as_function(stats::as.formula(paste("~", gsub("x", ".x", .x))))
      )
    )

  # load canonical unit of VE data variables
  # this YAML file is generated by tools/R/build_data_variables_table.R, which
  # should be re-run once when there is any update to VE's data variable TOML
  units <-
    build_data_variables_table() |>
    tibble::enframe(name = "var_canonical") |>
    tidyr::unnest_wider(value) |>
    dplyr::select(var_canonical, unit_to = unit)

  # Ingest datasets --------------------------------------------------------

  # path to source datasets
  sources_dir <- file.path(config_dir, "sources")
  sources_files <- list.files(
    sources_dir,
    pattern = "\\.yaml$",
    full.names = TRUE
  )

  # read the metadata of data sources
  sources <-
    sources_files |>
    purrr::map(yaml::read_yaml) |>
    # filter and keep only sources that has the source_id entry
    purrr::keep(~ purrr::pluck_exists(.x, "source_id"))

  # Harmonise each dataset
  data_harmonised <-
    sources |>
    purrr::map(\(source_dat) {
      # read dataset csv file
      readr::read_csv(
        source_dat$data_file,
        show_col_types = FALSE,
        skip = source_dat$skip_rows
      ) |>
        # select the relevant columns: unique IDs and validation variables
        dplyr::select(tidyr::all_of(c(
          source_dat$dedup_key,
          names(source_dat$variables)
        ))) |>
        # combine dedup keys into a single ID column
        tidyr::unite("ID", tidyr::all_of(source_dat$dedup_key)) |>
        # pivot to long format because this is the easiest way to convert units and
        # remove NAs
        tidyr::pivot_longer(
          cols = names(source_dat$variables),
          names_to = "var_original"
        ) |>
        dplyr::filter(!is.na(value)) |>
        # join variable information,
        # including unit and target validation variable
        dplyr::left_join(
          source_dat$variables |>
            tibble::enframe(name = "var_original") |>
            tidyr::unnest_wider(value),
          by = dplyr::join_by(var_original)
        ) |>
        # Unit conversion
        dplyr::rename(unit_from = unit) |>
        # join canonical or target units
        dplyr::left_join(units, by = dplyr::join_by(var_canonical)) |>
        # join conversion function
        dplyr::left_join(
          unit_conversions,
          by = dplyr::join_by(unit_from, unit_to)
        ) |>
        # convert the unit finally
        dplyr::mutate(
          value_canonical = purrr::map2_dbl(value, convert_unit, ~ .y(.x))
        ) |>
        # add the source ID
        dplyr::mutate(dataset = source_dat$source_id)
    })

  # combine datasets into a database
  database <-
    data_harmonised |>
    purrr::list_rbind() |>
    dplyr::select(
      dataset,
      ID,
      var_original,
      value_original = value,
      var_canonical,
      unit_from,
      unit_to,
      value_canonical
    )

  # Write database ---------------------------------------------------------
  database |>
    dplyr::group_by(dataset) |>
    arrow::write_dataset(db_path, format = "parquet")

  # print message on write
  cli::cli_alert_success("Database saved to {db_path}.")
}


#' Build a table of canonical VE and derived variables
#'
#' Compile the metadata of canonical VE data variables, which are maintained on
#' the virtual_ecosystem repository, and optionally append a custom table of
#' derived or emergent variables not defined in VE. This function is expected
#' to be ran whenever there is an update to the VE data variables or the custom
#' derived variables. This helper function is unexported.
#'
#' @param variables_ve Path or URL to the virtual_ecosystem's data variable TOML
#'   table.
#' @param variables_derived Path to the custom derived variable TOML table.
#'   Currently it defaults to the soil module.
#'
#' @returns A list of metadata of canonical VE and/or derived data variables.

build_data_variables_table <- function(
  variables_ve = "https://github.com/ImperialCollegeLondon/virtual_ecosystem/raw/refs/heads/develop/virtual_ecosystem/data_variables.toml",
  variables_derived = "data/derived/soil/validation/config/derived_variables.toml"
) {
  var_list <- import_variables_table(variables_ve)
  if (!is.null(variables_derived)) {
    var_list <- c(var_list, import_variables_table(variables_derived))
  }
  return(var_list)
}


#' Import data variable TOML table into a tidy list
#'
#' This is an unexported helper function for [build_data_variables_table()].
#'
#' @param toml Path or URL to the virtual_ecosystem's data variable TOML
#'   table.
#'
#' @returns

import_variables_table <- function(toml) {
  toml::read_toml(toml) |>
    purrr::pluck("variable") |>
    {
      \(x) purrr::set_names(x, purrr::map_chr(x, "name"))
    }() |>
    purrr::map(~ purrr::discard(.x, names(.x) == "name"))
}
