#| ---
#| title: Functions to build a validation database
#|
#| description: |
#|     Here we use a config-driven pipeline to read, wrangle, unit-convert, and
#|     combine multiple datasets into a single master file, hereafter referred to as
#|     the "validation database". We are not aiming for a full database backend, instead
#|     the main goal is to avoid having to write many custom codes that each only work
#|     for one dataset. The idea to run a single script to build the database, while YAML
#|     config metadata handles all dataset-specific idiosyncracies.
#|     Please refer to `docs/validation_database.md` for a full documentation.
#|
#| virtual_ecosystem_module: [Soil, Litter]
#|
#| author: Hao Ran Lai
#|
#| status: final
#|
#| input_files:
#|
#| output_files:
#|
#| package_dependencies:
#|     - arrow
#|     - cli
#|     - dplyr
#|     - purrr
#|     - rcrossref
#|     - readr
#|     - rlang
#|     - stats
#|     - tibble
#|     - tidyr
#|     - toml
#|     - utils
#|     - yaml
#|     - yesno
#|
#| usage_notes: |
#|   Please refer to `docs/validation_database.md` for a step-by-step tutorial.
#| ---

#' Log decision on whether a dataset should be included for validation purposes
#'
#' This function is intended to be used as \code{log_dataset()}, which will display
#' a UI in the R console and prompt you to enter the DOI and notes on
#' decisions. The log is then stored as a human-readable YAML file in the
#' specified output path, which defaults to the soil module for now.
#'
#' @param filename Filename of the source metadata, which currently defaults
#'   to the soil module
#'
#' @details
#' You will asked to enter:
#' \describe{
#'   \item{DOI}{DOI string of the dataset or publication}
#'   \item{Decision}{A menu to select decision}
#'   \item{Reason}{(Optional) A menu to select reason}
#'   \item{Notes}{(Optional) A string of long-form rationale}
#' }
#'
#' @returns A YAML file logging the decision and source metadata in
#'   \code{filename}.
#'
#' @export
#'
#' @examples
#' box::use(tools/R/R/valdb)
#' box::help(valdb$log_dataset)  # if you need a conventional R help page
#' valdb$log_dataset()

log_dataset <- function(
  filename = "data/derived/soil/validation/config/sources.yaml"
) {
  # prompt to enter DOI
  doi_input <- readline("Enter DOI: ")

  # normalise DOI to ensure consistency
  doi <- normalise_doi(doi_input)

  # read source yaml file if it already exists
  if (file.exists(filename)) {
    sources <- yaml::read_yaml(filename)
    # exit early if a DOI has already been logged
    doi_existing <- purrr::map_chr(sources, "doi")
    if (doi %in% normalise_doi(doi_existing)) {
      cli::cli_abort("{.val {doi}} has already been logged in {filename}.")
    }
  }

  # download dataset metadata
  meta <- rcrossref::cr_cn(doi, format = "bibentry")

  # prompt for decision, decision, decision...
  decision <- utils::select.list(
    c("included", "excluded"),
    title = "Decision (enter 0 to skip): ",
    graphics = FALSE
  )
  if (decision == "") {
    decision <- "skipped"
  }

  # prompt for short-form reason
  reason <- utils::select.list(
    c("used_elsewhere", "no_raw_data", "no_soil_data"),
    title = "Reason (enter 0 to skip): ",
    graphics = FALSE
  )

  # prompt for long-form notes
  notes <- readline("Notes (leave blank to skip): ")

  # Build new record
  new_record <- list(
    doi = meta$doi,
    decision = decision,
    reason = reason,
    notes = notes,
    logged_at = format(Sys.time(), "%Y-%m-%d"),
    metadata = list(
      title = meta$title,
      author = meta$author,
      year = meta$year,
      journal = as.character(meta$journal %||% NA),
      publisher = meta$publisher,
      url = meta$url,
      keywords = meta$keywords
    )
  )

  # append new record to existing source YAML if the latter already exists
  if (file.exists(filename)) {
    sources <- c(sources, list(new_record))
  } else {
    sources <- list(new_record)
  }

  # Write YAML
  yaml::write_yaml(sources, filename)

  # Completion message
  cli::cli_alert_info("Dataset from {.val {doi}} is {decision}")
  cli::cli_alert_success("Decision log saved to\n{filename}")
}


#' Add a template schema of dataset metadata and config
#'
#' @param source_yaml Filename of the dataset log YAML file. We expect this to
#'   have been generated by [log_dataset()].
#' @param doi DOI of the dataset to update in the source YAML.
#'
#' @returns An edited YAML config file replacing the previous unedited version.
#'
#' @export
#' @examples
#' box::use(tools/R/R/valdb)
#' valdb$add_schema(
#'   source_yaml = "data/derived/soil/validation/config/sources.yaml",
#'   doi = "10.5281/ZENODO.8158810"
#' )

add_schema <- function(
  source_yaml = "data/derived/soil/validation/config/sources.yaml",
  doi
) {
  # Validate input YAML exists before reading
  if (!file.exists(source_yaml)) {
    cli::cli_abort(c(
      "Source YAML not found: {.file {source_yaml}}",
      "Create it first with {.fn log_dataset}."
    ))
  }

  # Read existing YAML
  sources <- yaml::read_yaml(source_yaml)

  # Find target data source by DOI
  doi <- normalise_doi(doi)
  doi_list <- purrr::map_chr(sources, "doi")
  target_id <- which(normalise_doi(doi_list) == doi)

  # Abort unless DOI resolves to exactly one record
  if (length(target_id) != 1) {
    cli::cli_abort(
      "DOI {.val {doi}} appears {length(target_id)} times in {.file {source_yaml}}",
      "Expected exactly one match."
    )
  }

  # Default template schema
  template <- list(
    source_id = "author_year",
    data_file = "data/primary/soil/source_id/*.csv",
    skip_rows = 0L,
    variables = list(
      var_original_1 = list(
        var_canonical = "var_ve_1",
        unit = "unit",
        description = NA
      )
    ),
    dedup_key = c("sample_id", "date", "site_id"),
    # Spatial coordinates. Every entry below is OPTIONAL: datasets curated to
    # the SAFE standard need none of them, because the defaults already point
    # at the `locations.csv` exported from the `Locations` sheet. Delete the
    # entries you do not need, or delete the whole `coordinates` block.
    coordinates = list(
      # Path where the coordinates live.
      # Default: "locations.csv" next to `data_file`.
      from_file = NA,
      # Column name in `data_file` holding the location name.
      # Default: the first `dedup_key` entry.
      match_data_column = NA,
      # Column name in the locations file holding the location name.
      # Default: "Location name".
      match_location_column = NA,
      # Coordinate columns in the locations file.
      # Defaults: "Latitude" and "Longitude", in decimal degrees (WGS84).
      # NB: sources giving northing/easting instead will need
      # `coordinate_system` (an EPSG code) here, and a reprojection to
      # WGS84 in `add_coordinates()` via `sf::sf_project()`.
      latitude_column = NA,
      longitude_column = NA,
      # Use this INSTEAD of the entries above when the source gives only one
      # blanket location for every row, e.g. a study site named in the paper
      # but never pinned down per sample.
      same_for_all_rows = list(
        latitude = NA,
        longitude = NA,
        note = NA
      )
    )
  )

  # add the template entries to the target source YAML section
  sources[[target_id]] <- purrr::list_modify(sources[[target_id]], !!!template)

  # Write back
  yaml::write_yaml(sources, source_yaml)

  # Open the YAML file in the editor for editing
  utils::file.edit(source_yaml)
}


#' (Re)Build the validation database
#'
#' Build or rebuild the validation database based on the YAML configs of source
#' datasets.
#'
#' @param config_dir Path to where the dataset YAML config files are stored.
#' @param sources_file Filename of the source YAML metadata within
#'   \code{config_dir}, as generated by [log_dataset()] and later edited by
#'   [add_schema()].
#' @param db_path Output path for the harmonised database.
#'
#' @returns A harmonised database stored in db_path. Currently it is written out
#'   in the parquet format for efficient compression (and possibly appending).
#'   We may consider a plain csv in the future.
#'
#' @export
#' @examples
#' box::use(tools/R/R/valdb)
#' valdb$build_validation_database()

build_validation_database <- function(
  config_dir = "data/derived/soil/validation/config",
  sources_file = "sources.yaml",
  db_path = "data/derived/soil/validation/database"
) {
  # Configs ----------------------------------------------------------------

  # load canonical unit of VE data variables
  # this YAML file is generated by tools/R/build_data_variables_table.R, which
  # should be re-run once when there is any update to VE's data variable TOML
  units <-
    build_data_variables_table() |>
    tibble::enframe(name = "var_canonical") |>
    tidyr::unnest_wider(value) |>
    dplyr::select(var_canonical, unit_canonical = unit) |>
    # remove elements denoted in the curly brackets
    # because we do not need them for the subsequent unit conversion
    dplyr::mutate(
      unit_canonical = stringr::str_remove_all(unit_canonical, "\\{[^}]+\\}")
    )

  # Ingest datasets --------------------------------------------------------

  # read the metadata of data sources from a single YAML file, and then
  # filter to keep only sources that have the source_id entry
  sources <-
    file.path(config_dir, sources_file) |>
    yaml::read_yaml() |>
    purrr::keep(~ purrr::pluck_exists(.x, "source_id"))

  if (length(sources) == 0) {
    cli::cli_abort(
      "No source in {.file {file.path(config_dir, sources_file)}} has a
       {.field source_id}. Run {.fn add_schema} on a source first."
    )
  }

  # Harmonise each dataset ------------------------------------------------
  data_harmonised <-
    sources |>
    purrr::map(\(src) {
      # read dataset csv file
      readr::read_csv(
        src$data_file,
        show_col_types = FALSE,
        skip = src$skip_rows
      ) |>
        # select the relevant columns: unique IDs and validation variables
        dplyr::select(tidyr::all_of(c(
          src$dedup_key,
          names(src$variables)
        ))) |>
        # attach spatial coordinates while the data is still one row per
        # observation, and before `unite()` consumes the dedup key columns
        add_coordinates(src) |>
        # combine dedup keys into a single ID column
        tidyr::unite("ID", tidyr::all_of(src$dedup_key)) |>
        # pivot to long format because this is the easiest way to convert units
        # and remove NAs
        tidyr::pivot_longer(
          cols = names(src$variables),
          names_to = "var_original"
        ) |>
        dplyr::filter(!is.na(value)) |>
        # join variable information,
        # including unit and target validation variable
        dplyr::left_join(
          src$variables |>
            tibble::enframe(name = "var_original") |>
            tidyr::unnest_wider(value) |>
            dplyr::rename(unit_original = unit),
          by = dplyr::join_by(var_original)
        ) |>
        # Unit conversion
        # join canonical or target units
        dplyr::left_join(units, by = dplyr::join_by(var_canonical)) |>
        # convert unit character string to units class
        dplyr::mutate(
          unit_canonical = purrr::map(unit_canonical, units::as_units),
          unit_original = purrr::map(unit_original, units::as_units)
        ) |>
        # assign units to data values
        # we need to use map2 because units does not accept mixed unit columns
        dplyr::mutate(
          value = purrr::map2(value, unit_original, \(x, y) {
            x * y
          })
        ) |>
        # convert the unit finally
        dplyr::mutate(
          value_canonical = purrr::map2(value, unit_canonical, \(x, y) {
            units::set_units(x, y, mode = "standard")
          })
        ) |>
        # add the source ID
        dplyr::mutate(dataset = src$source_id)
    })

  # combine datasets into a database
  database <-
    data_harmonised |>
    purrr::list_rbind() |>
    dplyr::select(
      dataset,
      ID,
      latitude,
      longitude,
      location_type,
      coordinate_source,
      var_original,
      value_original = value,
      unit_original,
      var_canonical,
      unit_canonical,
      value_canonical
    )

  # Write database ---------------------------------------------------------
  database |>
    dplyr::group_by(dataset) |>
    arrow::write_dataset(db_path, format = "parquet")

  # print message on write
  cli::cli_alert_success("Database saved to {db_path}.")
}


#' Attach spatial coordinates to a source dataset
#'
#' This is an unexported helper for [build_validation_database()]. It adds four
#' columns to a dataset: \code{latitude}, \code{longitude},
#' \code{location_type} and \code{coordinate_source}.
#'
#' Most SAFE Zenodo datasets need no configuration at all, because they are
#' curated to a common standard: a \code{Locations} sheet holding
#' \code{Location name}, \code{Latitude} and \code{Longitude} in decimal
#' degrees (WGS84). Following the manual-conversion convention for the data
#' sheet, export that sheet to \code{locations.csv} in the same folder as
#' \code{data_file} and this function will find it automatically.
#'
#' Datasets that deviate are handled by the optional \code{coordinates} block
#' in the source YAML; see [add_schema()] for the annotated template.
#'
#' @param dat A dataset that is one row per observation, still carrying its raw
#'   \code{dedup_key} columns.
#' @param src One source entry from the source YAML metadata.
#'
#' @returns \code{dat} with the four coordinate columns added. The row count is
#'   guaranteed to be unchanged.

add_coordinates <- function(dat, src) {
  spec <- drop_blanks(src$coordinates)
  n_before <- nrow(dat)

  # Case 1: one blanket coordinate for the whole dataset
  blanket <- drop_blanks(spec$same_for_all_rows)
  if (length(blanket) > 0) {
    if (is.null(blanket$latitude) || is.null(blanket$longitude)) {
      cli::cli_abort(
        "{.field same_for_all_rows} in {.val {src$source_id}} needs both
         a {.field latitude} and a {.field longitude}. You are getting this
         because you specified something in {.field same_for_all_rows} but left
         {.field latitude} and a {.field longitude} as blank."
      )
    }
    return(dplyr::mutate(
      dat,
      latitude = as.numeric(blanket$latitude),
      longitude = as.numeric(blanket$longitude),
      location_type = "whole dataset",
      coordinate_source = "same_for_all_rows"
    ))
  }

  # Case 2: look the coordinates up from a locations file
  locations_file <- spec$from_file %||%
    file.path(dirname(src$data_file), "locations.csv")

  if (!file.exists(locations_file)) {
    cli::cli_warn(
      "No coordinates for {.val {src$source_id}}: cannot find
       {.file {locations_file}}. Export the {.field Locations} sheet of the
       source file to that path, or add a {.field coordinates} block to the
       source YAML. Currently NA coordinates are assigned for
       {.val {src$source_id}}"
    )
    return(dplyr::mutate(
      dat,
      latitude = NA_real_,
      longitude = NA_real_,
      location_type = NA_character_,
      coordinate_source = "missing"
    ))
  }

  # the column in `dat` naming the location: default to the dedup key, but
  # only when that key is unambiguous
  key_data <- spec$match_data_column
  if (is.null(key_data)) {
    if (length(src$dedup_key) > 1) {
      cli::cli_abort(
        "{.val {src$source_id}} has a multi-column {.field dedup_key},
         so the location column is ambiguous. Name it explicitly with
         {.field coordinates: match_data_column} in the source YAML."
      )
    }
    key_data <- src$dedup_key
  }

  # gather the location coordinates
  locations <-
    readr::read_csv(locations_file, show_col_types = FALSE) |>
    dplyr::select(
      location_key = tidyr::all_of(
        spec$match_location_column %||% "Location name"
      ),
      latitude = tidyr::all_of(spec$latitude_column %||% "Latitude"),
      longitude = tidyr::all_of(spec$longitude_column %||% "Longitude"),
      # `Type` records how the location was defined, e.g. "POINT" or
      # "Carbon Plot". It is absent in non-SAFE locations files.
      location_type = tidyr::any_of("Type")
    ) |>
    dplyr::mutate(dplyr::across(c(latitude, longitude), as.numeric))

  if (!"location_type" %in% names(locations)) {
    locations$location_type <- NA_character_
  }

  # join locations to the data
  dat <-
    dat |>
    dplyr::left_join(
      locations,
      # setNames() because the column name comes from a variable
      by = stats::setNames("location_key", key_data),
      # errors if the locations file has duplicated keys, which would
      # silently inflate the number of observations
      # NB: many-to-one should also cover one-to-one
      relationship = "many-to-one"
    ) |>
    # cover the case of partial missingness in a location file
    dplyr::mutate(
      coordinate_source = dplyr::if_else(
        is.na(latitude) | is.na(longitude),
        "missing",
        "locations_file"
      )
    )

  # check the join in case the dplyr::left_join `relationship` argument is
  # ever relaxed
  if (nrow(dat) != n_before) {
    cli::cli_abort(
      "Joining coordinates changed the number of rows of
       {.val {src$source_id}} from {n_before} to {nrow(dat)}."
    )
  }

  validate_coordinates(dat, src$source_id)

  dat
}


#' Sanity-check the coordinates of one source dataset
#'
#' An unexported helper for [add_coordinates()]. Out-of-range coordinates are
#' an error, because they usually mean the columns were swapped or are in a
#' projected coordinate system rather than decimal degrees. Missing
#' coordinates are only a warning, because some curated locations genuinely
#' have none.
#'
#' @param dat A dataset with \code{latitude} and \code{longitude} columns.
#' @param source_id The source ID, used in messages.
#'
#' @returns \code{dat}, invisibly.

validate_coordinates <- function(dat, source_id) {
  out_of_range <- dat |>
    dplyr::filter(
      !dplyr::between(latitude, -90, 90) |
        !dplyr::between(longitude, -180, 180)
    )

  if (nrow(out_of_range) > 0) {
    cli::cli_abort(
      c(
        "{nrow(out_of_range)} row{?s} of {.val {source_id}} have coordinates
         outside the valid range.",
        "i" = "Coordinates must be decimal degrees (WGS84). Are the latitude
               and longitude columns swapped, or projected?"
      )
    )
  }

  n_missing <- sum(dat$coordinate_source == "missing")
  if (n_missing > 0) {
    cli::cli_warn(
      "{n_missing} of {nrow(dat)} row{?s} of {.val {source_id}} have no
       coordinates."
    )
  }

  invisible(dat)
}


#' Drop empty entries from a YAML config block
#'
#' An unexported helper. Template entries left as \code{NA} in the source YAML
#' are treated as "not supplied", so that curators can delete or ignore the
#' fields they do not need.
#'
#' @param x A list read from the source YAML, possibly \code{NULL}.
#'
#' @returns A list with \code{NULL}, \code{NA} and empty-string entries removed.

drop_blanks <- function(x) {
  if (is.null(x)) {
    return(list())
  }
  purrr::discard(x, \(entry) {
    is.null(entry) ||
      (length(entry) == 0) ||
      (length(entry) == 1 && is.atomic(entry) && (is.na(entry) || entry == ""))
  })
}


#' Build a table of canonical VE and derived variables
#'
#' Compile the metadata of canonical VE data variables, which are maintained on
#' the virtual_ecosystem repository, and optionally append a custom table of
#' derived or emergent variables not defined in VE. This function is expected
#' to be ran whenever there is an update to the VE data variables or the custom
#' derived variables. This helper function is unexported.
#'
#' @param variables_ve Path or URL to the virtual_ecosystem's data variable TOML
#'   table.
#' @param variables_derived Path to the custom derived variable TOML table.
#'   Currently it defaults to the soil module.
#'
#' @returns A list of metadata of canonical VE and/or derived data variables.

build_data_variables_table <- function(
  variables_ve = "https://github.com/ImperialCollegeLondon/virtual_ecosystem/raw/refs/heads/develop/virtual_ecosystem/data_variables.toml",
  variables_derived = "data/derived/soil/validation/config/derived_variables.toml"
) {
  var_list <- import_variables_table(variables_ve)
  if (!is.null(variables_derived)) {
    var_list <- c(var_list, import_variables_table(variables_derived))
  }
  return(var_list)
}


#' Import data variable TOML table into a tidy list
#'
#' This is an unexported helper function for [build_data_variables_table()].
#'
#' @param toml Path or URL to the virtual_ecosystem's data variable TOML
#'   table.
#'
#' @returns

import_variables_table <- function(toml) {
  toml::read_toml(toml) |>
    purrr::pluck("variable") |>
    {
      \(x) purrr::set_names(x, purrr::map_chr(x, "name"))
    }() |>
    purrr::map(~ purrr::discard(.x, names(.x) == "name"))
}

#' Normalise DOI strings for consistent handling
#'
#' Normalises DOI strings by removing common URL prefixes, trimming whitespace,
#' and converting to uppercase. This ensures consistent DOI representation
#' across the database and supports downstream processing.
#'
#' @param doi A character vector of DOI strings to normalise.
#'
#' @returns A character vector of normalised DOI strings in the format `10.XXXX/XXXXX`
#'   (uppercase, whitespace trimmed, URL prefixes removed).
#'
#' @export
#'
#' @examples
#' # Clean DOI suffix
#' normalise_doi("10.1038/nphys1170")
#'
#' # Uppercase DOI
#' normalise_doi("10.1038/NPHYS1170")
#'
#' # Full HTTPS URL
#' normalise_doi("https://doi.org/10.1038/nphys1170")
#'
#' # Legacy HTTP DX URL
#' normalise_doi("http://dx.doi.org/10.1038/nphys1170")
#'
#' # DOI prefix format
#' normalise_doi("doi:10.1038/nphys1170")
#'
#' # With surrounding whitespace
#' normalise_doi(" 10.1038/nphys1170 ")
#'
#' # Vector of mixed formats
#' normalise_doi(c(
#'   "10.1038/nphys1170",
#'   "https://doi.org/10.1038/nphys1170",
#'   "DOI:10.1038/NPHYS1170"
#' ))

normalise_doi <- function(doi) {
  if (!is.character(doi)) {
    rlang::abort(
      c(
        "Argument {.arg doi} must be a character vector.",
        "Got {.cls {class(doi)}}."
      )
    )
  }

  # Trim whitespace
  doi <- stringr::str_trim(doi)

  # Remove common URL prefixes (case-insensitive)
  doi <- stringr::str_remove(doi, "^(?i)https?://(?:dx\\.)?doi\\.org/")
  doi <- stringr::str_remove(doi, "^(?i)doi:")

  # Convert to uppercase
  doi <- stringr::str_to_upper(doi)

  return(doi)
}
