project:
  type: website
  output-dir: docs
  render:
    - experimental/
    - manual/
    - index.qmd

website:
  title: "VE data science"
  description: "The Virtual Ecosystem data science repository"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Manuals"
        menu:
          - manual/getting_started.qmd
          - manual/github_overview.qmd
          - manual/using_globus.qmd
          - manual/uploading_r_scripts.qmd
          - manual/what_are_those_odd_files.qmd
    tools:
      - icon: github
        menu:
          - text: Source code
            href: https://github.com/ImperialCollegeLondon/ve_data_science
          - text: Report an issue
            href: https://github.com/ImperialCollegeLondon/ve_data_science/issues
  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
