[tool.poetry]
authors = [
  "Rob Ewers <r.ewers@imperial.ac.uk>",
  "David Orme <d.orme@imperial.ac.uk>",
  "Jacob Cook <j.cook17@imperial.ac.uk>",
  "Vivienne Groner <v.groner@imperial.ac.uk>",
  "Taran Rallings <t.rallings@imperial.ac.uk>",
  "Olivia Daniel <olivia.daniel08@imperial.ac.uk>",
  "Jaideep Joshi <joshi@iiasa.ac.at>",
  "Anna Rallings <a.rallings@imperial.ac.uk>",
  "Priyanga Amarasekare <pamarasekare@gmail.com>",
]
description = "A repository for the data science code for the Virtual Ecosystem"
license = "BSD-3-Clause"
name = "ve_data_science"
package-mode = false
readme = "README.md"
repository = "https://github.com/ImperialCollegeLondon/ve_data_science"
version = "0.1.0"

[tool.poetry.dependencies]
globus-cli = "^3.32.0"
globus-sdk = "3.46.0"
ipython = "^8.32.0"
jupyterlab = "^4.3.5"
jupyterlab-myst = "^2.4.2"
jupytext = "^1.16.7"
marshmallow = "^3.26.1"
marshmallow-dataclass = "^8.7.1"
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.12"
numpy = "^2.1"
pre-commit = "^4.1.0"
python = ">=3.10,<3.13"
pyyaml = "^6.0.2"
radian = "^0.6.13"
ruff = "^0.9.3"
xarray = "^2025.1.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
# Enable all `pydocstyle` rules, limiting to those that adhere to the
# Google convention via `convention = "google"`, below.
select = [
  "E", # pycodestyle
  "F", # pyflakes
  "D", # pydocstyle
  "I", # isort
  "UP", # pyupgrade
  "RUF", # ruff-only checking
  "NPY201", # Numpy 2.0.1
]

# On top of the Google convention, disable:
ignore = [
  "D202", # Blank line after docstring is ok
  "D107", # Location of __init__ docstring in class not __init__"
]

[tool.jupytext]
# Stop jupytext from removing mystnb and other settings in MyST Notebook YAML headers
notebook_metadata_filter = "settings,mystnb,language_info,ve_data_science,-jupytext.text_representation.jupytext_version"
# Also stop it from stripping cell metadata, except for specific ones to lose.
cell_metadata_filter = "all,-trusted"
