library(tidyverse)
library(readxl)
library(RcppTOML)
library(sf)
library(terra)
library(autoFRK)
library(CBFM)
library(RNetCDF)
library(glmmTMB)
library(biogas)
library(lubridate)
library(hms)
source("tools/R/convert_df_to_nc.R")

set.seed(20260703)
