#| ---
#| title: Spatial model to predict initial soil variables
#|
#| description: |
#|     This R script builds a spatial regression model to predict initial
#|     soil values to run VE. Currently it is parameterised with the soil
#|     campaign at SAFE. The choice of spatial covariates subjected to
#|     ongoing discussions. Towards the end, a prediction is made for the
#|     Maliau region. The model and its prediction are intended to be used
#|     in downstream analyses that further split the coarse variables into
#|     separate soil pools.
#|
#| virtual_ecosystem_module: Soil
#|
#| author: Hao Ran Lai
#|
#| status: wip
#|
#| input_files:
#|   - name: SRTM_UTM50N_processed.tif
#|     path: data/primary/abiotic/STRM_data_elevation
#|     description: |
#|       SRTM elevation data for the SAFE Project from
#|       https://zenodo.org/records/3490488
#|   - name: SRTM_UTM50N_TRI_Wilson2007.tif
#|     path: data/primary/abiotic/SAFE_topographic_roughness
#|     description: |
#|       SAFE topographic roughness from https://zenodo.org/records/3697796
#|   - name: SRTM_Log_Flow_Accum.tif
#|     path: data/primary/abiotic/SRTM_hydrology
#|     description: |
#|       SRTM derived flow accumulation for the SAFE Project from
#|       https://zenodo.org/records/3490687
#|   - name: Danum_acd.tif
#|     path: data/primary/abiotic/remote_biomass
#|     description: |
#|       Danum Valley above-ground carbon density from LiDAR
#|       https://zenodo.org/records/4020697
#|   - name: Danum_acd.tif
#|     path: data/primary/abiotic/remote_biomass
#|     description: |
#|       Danum Valley above-ground carbon density from LiDAR
#|       https://zenodo.org/records/4020697
#|   - name: Maliau_acd.tif
#|     path: data/primary/abiotic/remote_biomass
#|     description: |
#|       Maliau above-ground carbon density from LiDAR
#|       https://zenodo.org/records/4020697
#|   - name: SAFE_acd.tif
#|     path: data/primary/abiotic/remote_biomass
#|     description: |
#|       SAFE above-ground carbon density from LiDAR
#|       https://zenodo.org/records/4020697
#|   - name: Sabah_EVI_2024_Q1.tif
#|     path: data/primary/abiotic/remote_biomass
#|     description: |
#|       Enhanced Vegetation Index using the Sentinel-2 cloudless quarterly
#|       mosaics, generated by Jacob Cook
#|   - name: maliau_grid_definition_100m.toml
#|     path: data/derived/site
#|     description: |
#|       Maliau grid definition at 100-m resolution for the scenario run
#|   - name: gazetteer.geojson
#|     path: data/primary/site
#|     description: |
#|       SAFE gazetteer for plot coordinates from
#|       https://zenodo.org/records/3906082
#|   - name: SAFE_soil_nutrient_data.xlsx
#|     path: data/primary/soil/nutrient
#|     description: |
#|       SAFE soil nutrient campaign data by Jacob Cook, to be uploaded to
#|       the SAFE Zenodo repository
#|
#| output_files:
#|
#| package_dependencies:
#|     - tidyverse
#|     - readxl
#|     - RcppTOML
#|     - sf
#|     - terra
#|     - autoFRK
#|     - CBFM
#|     - modelr
#|
#| usage_notes: |
#|     The CBFM needs to be installed from https://github.com/fhui28/CBFM
#| ---

library(tidyverse)
library(readxl)
library(RcppTOML)
library(sf)
library(terra)
library(autoFRK)
library(CBFM)
library(modelr)


# Data --------------------------------------------------------------------

# Predictors (under discussion with Jacob Cook)

# Elevation
# STRM-derived data
elev <-
  rast("data/primary/abiotic/STRM_data_elevation/SRTM_UTM50N_processed.tif")

# Topography
topo <-
  rast(
    "data/primary/abiotic/SAFE_topographic_roughness/SRTM_UTM50N_TRI_Wilson2007.tif"
  )

# Climate
# Not included now

# Hydrology
hydro <-
  rast("data/primary/abiotic/SRTM_hydrology/SRTM_Log_Flow_Accum.tif")

# LiDAR
acd <-
  merge(
    rast("data/primary/plant/remote_biomass/Danum_acd.tif"),
    rast("data/primary/plant/remote_biomass/Maliau_acd.tif"),
    rast("data/primary/plant/remote_biomass/SAFE_acd.tif")
  )
names(acd) <- "acd"

# Biomass
evi <-
  rast("data/primary/plant/remote_biomass/Sabah_EVI_2024_Q1.tif")

# Location details
maliau <-
  parseTOML("data/derived/site/maliau/maliau_grid_definition_100m.toml")
# fill in missing coordinates
extra_locations <-
  tribble(
    ~location, ~lat, ~lon,
    "OG3_DW1", 4.733986, 116.970434,
    "OG3_DW2", 4.7341235, 116.967075,
    "OG3_DW3", 4.734606, 116.965199
  ) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326)
# tidy up location info
location_sf <-
  st_read("data/primary/site/gazetteer.geojson") %>%
  bind_rows(extra_locations) %>%
  st_transform(crs = st_crs(elev)) %>%
  st_centroid()
location <-
  location_sf %>%
  st_coordinates() %>%
  as.data.frame() %>%
  mutate(location = location_sf$location)

# Soil variables
soil <-
  read_xlsx(
    "data/primary/soil/nutrient/SAFE_soil_nutrient_data.xlsx",
    sheet = 3,
    skip = 4
  ) %>%
  left_join(location, by = join_by("plot_code" == "location")) %>%
  mutate(
    elev = extract(elev, .[, c("X", "Y")])[, "SRTM_UTM50N_processed"],
    topo = extract(topo, .[, c("X", "Y")])[, "SRTM_UTM50N_TRI_Wilson2007"],
    hydro = extract(hydro, .[, c("X", "Y")])[, "SRTM_Log_Flow_Accum"],
    acd = extract(acd, .[, c("X", "Y")])[, "acd"],
    evi = extract(evi, .[, c("X", "Y")])[, "EVI"]
  ) %>%
  drop_na(elev, topo, hydro, acd, evi)

# a list of selected soil response variables
soil_vars <-
  c(
    "pH",
    "bulk_density",
    "clay",
    "total_carbon",
    "total_nitrogen",
    "total_phosphorus",
    "available_phosphorus",
    "plot_mean_o_horizon"
  )

# create the soil response variable input matrix
soil_mat <- as.matrix(soil[, soil_vars])
soil_mat[, -c(1, 2)] <- log(soil_mat[, -c(1, 2)])
rownames(soil_mat) <- soil$plot_code

# scale covariates
soil_scaled <-
  soil %>%
  mutate_at(
    vars(elev, topo, hydro, acd, evi),
    ~ as.numeric(scale(.))
  )


# Model -------------------------------------------------------------------

# Set up spatial basis functions for CBFM
# Number of spatial basis functions to use
num_basis <- 25

# basis functions
basis_func <-
  mrts(soil_scaled[, c("X", "Y")], num_basis) %>%
  as.matrix() %>%
  # Remove the first intercept column
  {
    .[, -(1)]
  }

# Fit the CBFM model
fitcbfm <-
  CBFM(
    y = soil_mat,
    formula = ~ 1 + elev + topo + hydro + acd + evi,
    data = soil_scaled,
    B_space = basis_func,
    family = gaussian(),
    control = list(trace = 1),
    G_control = list(rank = 2)
  )
