"""
---
title: Morris screening analysis of hydrology module in the Virtual Ecosystem

description: |
  Performs the first-stage global sensitivity analysis of the Virtual Ecosystem
  (VE) hydrology module using the Morris screening method.

  The script analyses completed VE Morris simulations to identify hydrology
  parameters that have the greatest influence on selected hydrological
  responses. The analysis is intended to screen the full parameter set before
  the second-stage Sobol sensitivity analysis.

  The script first validates the Morris sampling design and checks that the
  parameter values used in the completed VE simulations match the intended
  design. It then extracts the required hydrological responses from the model
  outputs, removes the specified spin-up period, and performs basic model
  health checks.

  Morris elementary-effect statistics are calculated for scalar hydrological
  responses, with river discharge used as the primary response and other
  hydrological variables used as secondary responses. The analysis also
  evaluates sensitivity across the VE spatial grid and monthly time series to
  identify spatial and temporal changes in parameter influence.

  The results are used to screen the parameter set and identify candidate
  parameters for the subsequent Sobol analysis. Parameter selection is based
  on the Morris sensitivity results together with spatial, temporal, ranking
  stability, and model-health diagnostics.


virtual_ecosystem_module: Hydrology

author:
  - Lelavathy

status: wip

input_files:
  - name: arrayJob_config_<run_name>.toml
    path: data/sensitivity/hydrology/config/
    description: |
            Generated by morris_sample.py to run the Morris ensemble. Each sub-job
            contains one sampled set of constant values and corresponds to one row of
            the Morris design. The analysis reads this file to reconstruct and verify
            the design before matching it to model outputs.
  - name: sensitivity_parameters.toml
    path: data/sensitivity/hydrology/config/sensitivity_parameters.toml
    description: Bounds used for sampling. They must not change after sampling.
  - name: model_data.nc
    path: data/sensitivity/hydrology/out/<run_name>/<run folder>/model_data.nc
    description: |
            NetCDF output written by hpc_jobs/run_subJob.py for each completed
            array sub-job.

output_files:
  - name: Morris analysis folder
    path: data/sensitivity/hydrology/analysis/<run_name>/
    description: |
            Contains design and run-validation records, hydrological model-health
            checks, summaries of the output variables themselves (per run, in
            space and through time), Morris indices and screening decisions,
            ranking and spatial or monthly sensitivity results, figures, and a
            written summary. It also stores cached responses and the response
            specification used by the Sobol analysis; the hydrology results
            notebook reads its tables and figures.

imported_files:
    - name: sensitivity_tools.py
        path: tools/python/src/ve_data_tools/sensitivity_tools.py
    description: |
            Provides load_design and design_tables to reconstruct and validate the
            Morris design, find_run_outputs and verify_run_parameters to check the
            completed ensemble, and response functions to read model output, recover
            VE drainage sinks, cache responses, and save the response specification.
    - name: morris_analyse_tools.py
        path: tools/python/src/ve_data_tools/morris_analyse_tools.py
        description: |
            Calculates scalar, spatial, and monthly Morris indices; applies the
            screening rule; estimates ranking stability; and writes sensitivity
            figures, field-specific outputs, and the analysis summary.

package_dependencies:
  - numpy
  - pandas
  - xarray
  - scipy
  - matplotlib
  - SALib
  - pyprojroot

usage_notes: |
  1. Set run_name and the user settings below to match the completed ensemble.
     The default job_config, results_directory, replicate_directory, and
     analysis_directory are derived from this name.

  2. Check response_spec before analysis. It defines the spin-up period, model
     fields, outlet rule, and scalar responses. The Sobol analysis imports this
     specification, map_field, health_tolerance, and the hydrology health
     functions so both stages analyse the same responses.

  3. Run this analysis on the HPC system after all model runs finish. The
     current ensemble contains 300 VE runs; reading their NetCDF outputs can be
     resource-intensive, and future designs may contain substantially more runs.
     For larger future ensembles, request suitable memory, wall time, and CPUs,
     and keep --workers no higher than the allocated CPUs.

  4. For a small ensemble (a few hundred runs), run it interactively from the
     repository root on HPC:

     uv run python analysis/abiotic/sensitivity/morris_analyse_hydrology.py

  5. Use the PBS batch script instead of step 4 when the ensemble has about
     500 runs or more, or when the analysis should continue unattended after
     you log out:

        qsub data/sensitivity/hydrology/hpc_jobs/run_analyse_morris.pbs

     The script defaults to 4 CPUs, 8 GB memory, and 2 hours, which are
     starting values for a few hundred runs. It uses the number of allocated
     CPUs as --workers. For a larger ensemble, request more CPUs, memory, or
     wall time when submitting the same script. For example:

            qsub -l select=1:ncpus=4:mem=16gb -l walltime=04:00:00 \
                /hpc_jobs/run_analyse_morris.pbs

     Check the PBS output after the job finishes and increase the next memory
     or wall-time request if needed. Run either step 4 or step 5, not both.

  6. Review the design and run checks first. The script stops when the job-file
     design, parameter bounds, or parameters recorded by completed runs do not
     agree. Inspect model_health_by_run.csv before interpreting indices.

  7. Read the output-variable summaries (tables/output_*.csv, figures  and
     the "Output variables" part of summary.md) next to the indices. They show
     what the runs produced (ranges, negative values, drift, seasonality and
     spatial pattern), which is the evidence for interpreting the rankings.

  8. Use morris_screening_decision.csv, index tables, stability results, and
      model-health results to select Sobol constants manually.

note:  |
    1.  The Morris ensemble must be generated and completed before this analysis is
        run.

    2.  This script is specific to the hydrology module and its x/y-grid outputs.

    3.  The Morris results are used as a screening stage rather than as the final
        parameter importance analysis. Candidate parameters for the Sobol analysis
        should be selected after considering sensitivity magnitude, response
        relevance, spatial and temporal consistency, ranking stability, and model
        health.

references: |
    Morris, M. D. (1991). Factorial sampling plans for preliminary computational
    experiments. Technometrics, 33(2), 161-174.
    https://doi.org/10.1080/00401706.1991.10484804

    Campolongo, F., Cariboni, J., and Saltelli, A. (2007). An effective screening
    design for sensitivity analysis of large models. Environmental Modelling and
    Software, 22(10), 1509-1518. https://doi.org/10.1016/j.envsoft.2006.10.004

    Herman, J. D., Kollat, J. B., Reed, P. M., and Wagener, T. (2013). From maps
    to movies: High-resolution time-varying sensitivity analysis for spatially
    distributed watershed models. Hydrology and Earth System Sciences, 17,
    2893-2903. https://doi.org/10.5194/hess-17-2893-2013

Further information on SALib usage and supported sampling methods is available
in the SALib documentation: https://salib.readthedocs.io/en/latest
---
"""  # noqa: D400, D212, D205, D415

import argparse
import sys
import tomllib
from pathlib import Path

import numpy as np
import pandas as pd
from pyprojroot import here

project_root = here("pyproject.toml").parent
python_source = project_root / "tools" / "python" / "src"
if str(python_source) not in sys.path:
    sys.path.insert(0, str(python_source))

from ve_data_tools.morris_analyse_tools import (  # noqa: E402
    dominant_parameter_table,
    field_morris,
    morris_parameter_styles,
    plot_morris_overview,
    ranking_stability,
    scalar_morris,
    screening_decision,
    write_field_outputs,
    write_morris_summary,
)
from ve_data_tools.sensitivity_tools import (  # noqa: E402
    categorical_colours,
    design_tables,
    drainage_table,
    find_run_outputs,
    load_design,
    load_responses,
    pyplot,
    replicate_noise,
    save_figure,
    save_response_spec,
    to_model_space,
    ve_routing_from_output,
    verify_run_parameters,
)

# -----------------------------------------------------------------------------
# User settings: change these for every new experiment.
# -----------------------------------------------------------------------------

# Name of the run: the results folder under out/ and the analysis folder under
# analysis/. Can be changed on the command line with --run-name.
run_name = "hydrology_morris_001"

module_directory = project_root / "data/sensitivity/hydrology"

# The job file that was run is the design: the file morris_sample.py
# wrote for this run_name. Its header records the log10-sampled constants and
# the Morris levels, and the analysis reads both from there.
job_config = module_directory / "config" / f"arrayJob_config_{run_name}.toml"

# Bounds used for sampling. They must not have changed since sampling.
parameter_file = module_directory / "config" / "sensitivity_parameters.toml"

results_directory = module_directory / "out" / run_name
replicate_directory = module_directory / "out" / f"{run_name}_replicates"
analysis_directory = module_directory / "analysis" / run_name
model_output_name = "model_data.nc"  # written by hpc_jobs/run_subJob.py

# Number of parallel processes used to read completed VE NetCDF outputs.
# Set this no higher than the CPUs allocated to the interactive or PBS job;
n_workers = 4
# Override without editing the script, for example: --workers 8. When
# --use-cache reuses data/responses.npz, model outputs are not read and this
# setting has no effect.

# What is analysed. sobol_analyse_hydrology.py imports this block, so
# both stages always use the same responses (also saved to
# data/response_spec.json and compared by the Sobol analysis).
response_spec = {
    "simulation_start": "2010-01",  # core.timing.start_date
    "n_months": 132,  # core.timing.run_length / update_interval
    "grid_shape": (10, 10),  # (ny, nx); None to skip the check
    "spinup_months": 24,  # removed before any statistic
    # Layer-resolved variables -> single-layer fields.
    "layers": {
        "soil_moisture_topsoil": {
            "source": "soil_moisture",
            "dimension": "layers",
            "role": "topsoil",
        },
        "soil_moisture_subsoil": {
            "source": "soil_moisture",
            "dimension": "layers",
            "role": "subsoil",
        },
        # groundwater_layers has no coordinate values in VE output: position.
        "groundwater_storage_layer_1": {
            "source": "groundwater_storage",
            "dimension": "groundwater_layers",
            "position": 0,
        },
        "groundwater_storage_layer_2": {
            "source": "groundwater_storage",
            "dimension": "groundwater_layers",
            "position": 1,
        },
    },
    # Field -> monthly series: "outlet" (sum over VE's sink cells = total
    # outflow of the site) or "mean" (domain mean; right for local fluxes and
    # stores, which hold only their own cell's water).
    "fields": {
        "river_discharge_rate": "outlet",
        "surface_runoff_routed_plus_local": "outlet",
        "subsurface_runoff_routed_plus_local": "outlet",
        "surface_runoff": "mean",
        "subsurface_flow": "mean",
        "baseflow": "mean",
        "subsurface_stormflow": "mean",
        "bypass_flow": "mean",
        "soil_moisture_topsoil": "mean",
        "soil_moisture_subsoil": "mean",
        "groundwater_storage_layer_1": "mean",
        "groundwater_storage_layer_2": "mean",
    },
    # Outlets = VE's sinks, recovered exactly from the routed and local runoff
    # of the first run (no elevation file needed).e.g., hydrology_morris_001
    # has four sinks draining 55, 26, 11 and 8 of the 100 cells.
    # combine "sum" = whole-site outflow; "largest" = main catchment only.
    # Alternatives: {"method": "ve_sinks", "elevation_file": "<repo path>"}
    # or {"method": "xy", "x": ..., "y": ...} for one chosen cell.
    "outlet": {"method": "ve_routing", "combine": "sum"},
    #  River discharge rate is the primary response because it is the integrated,
    #  catchment-scale hydrological outcome used to assess the model. The
    #  remaining runoff pathways, water stores and local fluxes are secondary
    #  responses: they reveal the processes behind changes in discharge and can
    #  expose implausible behaviour. "Secondary" describes their role in the
    #  screening decision, not their scientific importance.
    "responses": [
        {
            "name": "discharge_mean",
            "variable": "river_discharge_rate",
            "statistic": "mean",
            "group": "primary",
        },
        {
            "name": "discharge_high_q90",
            "variable": "river_discharge_rate",
            "statistic": "q90",
            "group": "primary",
        },
        {
            "name": "discharge_low_q10",
            "variable": "river_discharge_rate",
            "statistic": "q10",
            "group": "primary",
        },
        # Feb-Mar are the driest months in the Maliau ERA5 input (~150-180 mm).
        {
            "name": "discharge_dry_season",
            "variable": "river_discharge_rate",
            "statistic": "mean",
            "group": "primary",
            "months": [2, 3],
        },
        {
            "name": "surface_runoff_outlet",
            "variable": "surface_runoff_routed_plus_local",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "subsurface_runoff_outlet",
            "variable": "subsurface_runoff_routed_plus_local",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "subsurface_flow",
            "variable": "subsurface_flow",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "baseflow",
            "variable": "baseflow",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "subsurface_stormflow",
            "variable": "subsurface_stormflow",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "bypass_flow",
            "variable": "bypass_flow",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "soil_moisture_topsoil",
            "variable": "soil_moisture_topsoil",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "soil_moisture_subsoil",
            "variable": "soil_moisture_subsoil",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "groundwater_storage_layer_1",
            "variable": "groundwater_storage_layer_1",
            "statistic": "mean",
            "group": "secondary",
        },
        {
            "name": "groundwater_storage_layer_2",
            "variable": "groundwater_storage_layer_2",
            "statistic": "mean",
            "group": "secondary",
        },
    ],
}

# Field whose maps the Sobol analysis draws (it imports this setting). The Morris
# analysis writes maps, monthly and dominant-parameter figures for every field
# in response_spec["fields"], in primary/<field>/ and secondary/<field>/.
map_field = "river_discharge_rate"
top_map_parameters = 4  # parameters mapped per field (2 x 2 panels)

# Morris analysis settings.
num_resamples = 1000  # bootstrap for mu*_conf, scalar responses
map_num_resamples = 100  # bootstrap for per-cell / per-month indices
conf_level = 0.95
screening_threshold = 0.10  # influential if mu* / max mu* >= this
secondary_support = 2  # candidate if influential for >= this many secondary
stability_bootstraps = 200  # trajectory resamples for ranking stability
top_k = 5  # "is the parameter in the top K?" in the stability table
health_tolerance = 5.0  # |water balance closure| allowed, % of rainfall
random_seed = 2026  # bootstrap seed (the design seed is in the job-file header)

# -----------------------------------------------------------------------------
# Hydrology model health (module-specific; also used by the Sobol analysis)
# -----------------------------------------------------------------------------


def model_health_table(paths: list) -> pd.DataFrame | None:
    """Water balance and state diagnostics of every run over the full ensemble.

    closure = P - (surface + subsurface + baseflow + stormflow + ET
                   + groundwater_loss) - change in soil and groundwater stores
    groundwater_loss is removed at every daily step in VE (30 days/month) and is
    read from compiled_configuration.toml. Also reported: minimum lower
    groundwater store, share of months with topsoil at saturation and subsoil
    at residual, mean soil vertical flow and surface runoff / rainfall.
    """
    import xarray as xr

    required = {
        "precipitation_surface",
        "surface_runoff",
        "subsurface_flow",
        "baseflow",
        "subsurface_stormflow",
        "soil_evaporation",
        "transpiration",
        "soil_moisture",
        "groundwater_storage",
        "vertical_flow",
    }
    rows = []
    for index, path in enumerate(paths, start=1):
        with xr.open_dataset(path) as ds:
            missing = required - set(ds.data_vars)
            if missing:
                print(f"   Note: model health skipped, missing {sorted(missing)}")
                return None
            total = lambda v: float(ds[v].mean(("x", "y")).sum())  # noqa: E731
            precipitation = total("precipitation_surface")
            surface = total("surface_runoff")
            runoff = sum(
                total(v)
                for v in (
                    "surface_runoff",
                    "subsurface_flow",
                    "baseflow",
                    "subsurface_stormflow",
                )
            )
            et = total("soil_evaporation") + float(
                ds["transpiration"].sum("layers").mean(("x", "y")).sum()
            )
            soil_layers = ds["layer_roles"].isin(["topsoil", "subsoil"])
            soil = ds["soil_moisture"].sel(layers=soil_layers)
            soil_total = soil.sum("layers").mean(("x", "y")).values
            groundwater = (
                ds["groundwater_storage"]
                .sum("groundwater_layers")
                .mean(("x", "y"))
                .values
            )
            top = soil.isel(layers=0).values
            sub = soil.isel(layers=1).values
            vertical = float(np.nanmean(ds["vertical_flow"].sel(layers=soil_layers)))
            lower_min = float(
                ds["groundwater_storage"].isel(groundwater_layers=1).min()
            )
            n_months = ds.sizes["time_index"]
        loss, saturation, residual = np.nan, np.nan, np.nan
        config = Path(path).parent / "compiled_configuration.toml"
        if config.exists():
            with config.open("rb") as handle:
                constants = tomllib.load(handle)["hydrology"]["constants"]
            loss = constants["groundwater_loss"] * 30 * n_months
            saturation = constants["soil_moisture_saturation"]
            residual = constants["soil_moisture_residual"]
        storage_change = (soil_total[-1] - soil_total[0]) + (
            groundwater[-1] - groundwater[0]
        )
        closure = precipitation - runoff - et - np.nan_to_num(loss) - storage_change
        rows.append(
            {
                "run": index,
                "precipitation_mm": precipitation,
                "runoff_mm": runoff,
                "evapotranspiration_mm": et,
                "groundwater_loss_mm": loss,
                "storage_change_mm": storage_change,
                "closure_percent_of_P": 100 * closure / precipitation,
                "runoff_over_precipitation": runoff / precipitation,
                "surface_runoff_share_of_P": surface / precipitation,
                "min_lower_groundwater_mm": lower_min,
                # topsoil 250 mm and subsoil 750 mm (core.layers.soil_layers)
                "months_topsoil_saturated": float(
                    np.mean(np.nanmean(top, axis=(1, 2)) >= 0.99 * 250 * saturation)
                ),
                "months_subsoil_at_residual": float(
                    np.mean(np.nanmean(sub, axis=(1, 2)) <= 1.01 * 750 * residual)
                ),
                "mean_soil_vertical_flow_mm": vertical,
            }
        )
    return pd.DataFrame(rows)


def report_model_health(table, path: Path, tolerance: float) -> list[str]:
    """Save the health table, print and return warnings."""
    if table is None:
        return []
    table.to_csv(path, index=False)
    notes = []
    n = len(table)
    bad = int((table["closure_percent_of_P"].abs() > tolerance).sum())
    negative = int((table["min_lower_groundwater_mm"] < 0).sum())
    pinned = int(
        (
            (table["months_topsoil_saturated"] > 0.9)
            & (table["months_subsoil_at_residual"] > 0.9)
        ).sum()
    )
    frozen = int((table["mean_soil_vertical_flow_mm"] < 1e-3).sum())
    if bad:
        notes.append(
            f"{bad} of {n} runs do not close the water balance within "
            f"+/-{tolerance}% of rainfall (median closure "
            f"{table['closure_percent_of_P'].median():.0f}%)."
        )
    if negative:
        notes.append(f"{negative} of {n} runs have negative lower groundwater storage.")
    if pinned:
        notes.append(
            f"{pinned} of {n} runs keep topsoil saturated and subsoil at "
            "residual in >90% of months."
        )
    if frozen:
        notes.append(f"{frozen} of {n} runs have (near) zero vertical soil flow.")
    for note in notes:
        print(f"   Warning: {note}")
    if notes:
        print(
            "   Indices then describe this model behaviour, not catchment "
            "hydrology. See " + path.name
        )
    return notes


# -----------------------------------------------------------------------------
# Output variables: what the ensemble produced, before any sensitivity index
# -----------------------------------------------------------------------------

# Units of the fields in response_spec["fields"]; every other field is in mm.
field_units = {"river_discharge_rate": "m3 s-1"}
near_zero = 1e-9  # |value| below this counts as zero
drift_flag = 0.10  # flag a drift larger than this share of |mean| over the period
uniform_flag = 0.01  # flag a coefficient of variation below this as "uniform"
month_names = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()


def unit_of(field: str) -> str:
    """Return the unit of a field (VE output units)."""
    return field_units.get(field, "mm")


def relative(numerator, denominator):
    """Return numerator / |denominator|, or NaN when that is (near) zero."""
    denominator = np.abs(denominator)
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(denominator > near_zero, numerator / denominator, np.nan)


def output_responses_by_run(problem: dict, samples, data: dict) -> pd.DataFrame:
    """One row per run: the constants it used (model units) and its responses."""
    table = pd.DataFrame(to_model_space(samples, problem), columns=problem["names"])
    table.insert(0, "run", np.arange(1, len(table) + 1))
    for column, name in enumerate(data["scalar_names"]):
        table[str(name)] = data["scalars"][:, column]
    return table


def output_summary_by_response(data: dict, spec: dict) -> pd.DataFrame:
    """Distribution of every scalar response across the runs."""
    variable = {r["name"]: r["variable"] for r in spec["responses"]}
    statistic = {r["name"]: r["statistic"] for r in spec["responses"]}
    rows = []
    for column, name in enumerate(data["scalar_names"]):
        name = str(name)
        values = data["scalars"][:, column]
        p05, median, p95 = np.quantile(values, [0.05, 0.5, 0.95])
        mean = values.mean()
        rows.append(
            {
                "response": name,
                "group": str(data["scalar_groups"][column]),
                "variable": variable[name],
                "statistic": statistic[name],
                "unit": unit_of(variable[name]),
                "n_runs": len(values),
                "min": values.min(),
                "p05": p05,
                "median": median,
                "mean": mean,
                "p95": p95,
                "max": values.max(),
                "cv_across_runs": float(relative(values.std(ddof=1), mean)),
                "p95_over_p05": float(relative(p95, p05)) if p05 > 0 else np.nan,
                "n_runs_negative": int((values < -near_zero).sum()),
                "n_runs_zero": int((np.abs(values) <= near_zero).sum()),
            }
        )
    return pd.DataFrame(rows)


def outlet_mask(data: dict) -> np.ndarray:
    """Boolean (ny, nx) mask of the outlet cells used for the "outlet" fields."""
    x, y = data["x"], data["y"]
    mask = np.zeros((len(y), len(x)), dtype=bool)
    for x_outlet, y_outlet in np.asarray(data["outlet_xy"], dtype=float):
        if np.isfinite(x_outlet) and np.isfinite(y_outlet):
            mask[np.argmin(np.abs(y - y_outlet)), np.argmin(np.abs(x - x_outlet))] = 1
    return mask


def output_spatial_summary(data: dict, spec: dict) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Long-term-mean maps: per-field summary and per-cell ensemble spread.

    ``data["maps"]`` is (runs, fields, y, x): each run's post-spin-up mean. The
    ensemble-median map is the median over runs in every cell.
    """
    x, y = data["x"], data["y"]
    outlets = outlet_mask(data)
    rows, cells = [], []
    for index, field in enumerate(data["fields"]):
        field = str(field)
        maps = data["maps"][:, index]
        p05, median, p95 = np.quantile(maps, [0.05, 0.5, 0.95], axis=0)
        row, col = np.unravel_index(np.argmax(median), median.shape)
        spread = relative(p95 - p05, median)
        rows.append(
            {
                "field": field,
                "rule": spec["fields"][field],
                "unit": unit_of(field),
                "cell_min": median.min(),
                "cell_median": np.median(median),
                "cell_max": median.max(),
                "spatial_cv": float(relative(median.std(ddof=1), median.mean())),
                "max_cell_x": x[col],
                "max_cell_y": y[row],
                "max_cell_is_outlet": bool(outlets[row, col]),
                "outlet_over_domain_mean": (
                    float(relative(median[outlets].mean(), median.mean()))
                    if outlets.any()
                    else np.nan
                ),
                "n_cells_negative_median_map": int((median < -near_zero).sum()),
                "n_runs_any_negative_cell": int(
                    (maps < -near_zero).any(axis=(1, 2)).sum()
                ),
                "between_run_spread_median": (
                    float(np.nanmedian(spread)) if np.isfinite(spread).any() else np.nan
                ),
            }
        )
        for r in range(len(y)):
            for c in range(len(x)):
                cells.append(
                    {
                        "field": field,
                        "x": x[c],
                        "y": y[r],
                        "is_outlet": bool(outlets[r, c]),
                        "p05": p05[r, c],
                        "median": median[r, c],
                        "p95": p95[r, c],
                    }
                )
    return pd.DataFrame(rows), pd.DataFrame(cells)


def output_temporal_summary(data: dict) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Monthly series: seasonality, drift and sign, per field.

    ``data["series"]`` is (runs, fields, months) after spin-up: the outlet sum
    for "outlet" fields and the domain mean for the others. Drift is the slope
    of each run's annual means, times the length of the period, relative to that
    run's mean: a store at steady state has a drift near zero.
    """
    dates = pd.to_datetime([str(d) for d in data["dates"]], format="%Y-%m")
    years = np.asarray(dates.year)
    months = np.asarray(dates.month)
    unique_years = np.unique(years)
    rows, climatology_rows = [], []
    for index, field in enumerate(data["fields"]):
        field = str(field)
        series = data["series"][:, index]  # (runs, months)
        run_mean = series.mean(axis=1)
        climatology = np.stack(
            [series[:, months == m].mean(axis=1) for m in range(1, 13)], axis=1
        )  # (runs, 12)
        clim_median = np.median(climatology, axis=0)
        annual = np.stack(
            [series[:, years == year].mean(axis=1) for year in unique_years], axis=1
        )
        slopes = np.polyfit(unique_years, annual.T, 1)[0]  # per run, unit per year
        span = unique_years[-1] - unique_years[0]
        drift = relative(slopes * span, run_mean)
        rows.append(
            {
                "field": field,
                "unit": unit_of(field),
                "median_of_run_means": float(np.median(run_mean)),
                "peak_month": month_names[int(np.argmax(clim_median))],
                "low_month": month_names[int(np.argmin(clim_median))],
                "seasonal_range_rel": float(
                    relative(clim_median.max() - clim_median.min(), np.median(run_mean))
                ),
                "median_trend_per_year": float(np.median(slopes)),
                "median_drift_rel": float(np.nanmedian(drift)),
                "n_runs_rising": int((drift > drift_flag).sum()),
                "n_runs_falling": int((drift < -drift_flag).sum()),
                "share_months_negative": float((series < -near_zero).mean()),
                "median_month_to_month_cv": float(
                    np.nanmedian(relative(series.std(axis=1, ddof=1), run_mean))
                ),
            }
        )
        p05, median, p95 = np.quantile(climatology, [0.05, 0.5, 0.95], axis=0)
        for m in range(12):
            climatology_rows.append(
                {
                    "field": field,
                    "month": month_names[m],
                    "p05": p05[m],
                    "median": median[m],
                    "p95": p95[m],
                }
            )
    return pd.DataFrame(rows), pd.DataFrame(climatology_rows)


def plot_output_overview(data: dict, spec: dict, figures: Path) -> None:
    """Three overview figures of the output variables across all runs."""
    plt = pyplot()
    colour = categorical_colours[0]
    fields = [str(f) for f in data["fields"]]
    n_runs = data["scalars"].shape[0]

    def grid(n_panels, width=3.4, height=2.4, n_cols=4):
        n_rows = int(np.ceil(n_panels / n_cols))
        fig, axes = plt.subplots(
            n_rows, n_cols, figsize=(width * n_cols, height * n_rows), squeeze=False
        )
        for axis in axes.flat[n_panels:]:
            axis.set_visible(False)
        return fig, axes.flat

    # Scalar responses across the runs
    names = [str(n) for n in data["scalar_names"]]
    variable = {r["name"]: r["variable"] for r in spec["responses"]}
    fig, axes = grid(len(names), height=1.8)
    for column, (axis, name) in enumerate(zip(axes, names)):
        values = data["scalars"][:, column]
        axis.boxplot(
            values,
            orientation="horizontal",
            widths=0.5,
            whis=(5, 95),
            patch_artist=True,
            boxprops={"facecolor": colour, "alpha": 0.35, "edgecolor": colour},
            medianprops={"color": colour, "linewidth": 2},
            flierprops={"marker": "o", "markersize": 3, "markeredgecolor": colour},
        )
        if values.min() > 0 and values.max() / values.min() > 100:
            axis.set_xscale("log")
        axis.set_title(name, fontsize=9)
        axis.set_yticks([])
        if axis.get_xscale() == "linear":
            axis.ticklabel_format(axis="x", useOffset=False)
        axis.set_xlabel(unit_of(variable[name]), fontsize=8)
        axis.tick_params(labelsize=7)
    fig.suptitle(f"Responses across {n_runs} runs (box 25-75%, whiskers 5-95%)")
    fig.tight_layout()
    save_figure(fig, figures / "06_output_distributions.png")

    # Monthly series: ensemble median and 5-95% band
    dates = pd.to_datetime([str(d) for d in data["dates"]], format="%Y-%m")
    fig, axes = grid(len(fields), width=3.6, height=2.3)
    for index, (axis, field) in enumerate(zip(axes, fields)):
        series = data["series"][:, index]
        p05, median, p95 = np.quantile(series, [0.05, 0.5, 0.95], axis=0)
        axis.fill_between(dates, p05, p95, color=colour, alpha=0.2, linewidth=0)
        axis.plot(dates, median, color=colour, linewidth=1.5)
        rule = spec["fields"][field]
        axis.set_title(f"{field} ({rule})", fontsize=8)
        axis.set_ylabel(unit_of(field), fontsize=8)
        axis.ticklabel_format(axis="y", useOffset=False)
        axis.tick_params(labelsize=7)
        axis.grid(alpha=0.3)
    fig.suptitle(f"Monthly series: median and 5-95% range over {n_runs} runs")
    fig.tight_layout()
    save_figure(fig, figures / "07_output_monthly_series.png")

    # Long-term-mean maps: ensemble median per cell
    outlets = outlet_mask(data)
    rows, cols = np.nonzero(outlets)
    fig, axes = grid(len(fields), width=3.2, height=2.9)
    for index, (axis, field) in enumerate(zip(axes, fields)):
        median = np.median(data["maps"][:, index], axis=0)
        if median.min() < -near_zero < near_zero < median.max():
            limit = np.abs(median).max()
            image = axis.imshow(median, cmap="RdBu", vmin=-limit, vmax=limit)
        else:
            image = axis.imshow(median, cmap="Blues")
        axis.scatter(cols, rows, marker="*", s=60, color="black", label="sink")
        axis.set_title(field, fontsize=8)
        axis.set_xticks([])
        axis.set_yticks([])
        colourbar = fig.colorbar(image, ax=axis, fraction=0.046, pad=0.04)
        colourbar.set_label(unit_of(field), fontsize=7)
        colourbar.ax.tick_params(labelsize=7)
    fig.suptitle(
        f"Long-term mean per cell: median over {n_runs} runs (north up; stars = sinks)"
    )
    fig.tight_layout()
    save_figure(fig, figures / "08_output_median_maps.png")


def output_findings(
    responses: pd.DataFrame,
    spatial: pd.DataFrame,
    temporal: pd.DataFrame,
    health: pd.DataFrame | None,
    tolerance: float,
) -> list[str]:
    """Plain statements of what the outputs show, for summary.md.

    These are evidence, not diagnoses: they describe the ensemble's outputs so
    the Morris indices can be read against them.
    """
    n_runs = int(responses["n_runs"].iloc[0])
    lines = [f"## Output variables ({n_runs} runs)", ""]

    if health is not None and len(health):
        closed = (health["closure_percent_of_P"].abs() <= tolerance).sum()
        lines += [
            "Water balance and stores (model_health_by_run.csv):",
            "",
            f"- {closed} of {len(health)} runs close the water balance within "
            f"+/-{tolerance:g}% of rainfall; median closure "
            f"{health['closure_percent_of_P'].median():.0f}% of rainfall.",
            "- Total runoff / rainfall: median "
            f"{health['runoff_over_precipitation'].median():.2f} (range "
            f"{health['runoff_over_precipitation'].min():.2f}-"
            f"{health['runoff_over_precipitation'].max():.3g}); surface runoff / "
            f"rainfall: median {health['surface_runoff_share_of_P'].median():.2f}.",
            f"- Lower groundwater store negative in "
            f"{(health['min_lower_groundwater_mm'] < 0).sum()} of {len(health)} runs.",
            f"- Mean soil vertical flow below 1e-3 mm in "
            f"{(health['mean_soil_vertical_flow_mm'].abs() < 1e-3).sum()} of "
            f"{len(health)} runs (median "
            f"{health['mean_soil_vertical_flow_mm'].median():.2g} mm).",
            "",
        ]

    lines += ["Responses across runs (output_summary_by_response.csv):", ""]
    for _, r in responses.iterrows():
        text = (
            f"- `{r['response']}` ({r['group']}): median {r['median']:.3g} "
            f"{r['unit']}, 5-95% {r['p05']:.3g} to {r['p95']:.3g}"
        )
        if r["n_runs_negative"]:
            text += f"; negative in {r['n_runs_negative']} runs"
        if r["cv_across_runs"] < uniform_flag:
            text += f"; hardly varies across runs (CV {r['cv_across_runs']:.2g})"
        lines.append(text + ".")

    lines += ["", "Through time (output_temporal_summary.csv):", ""]
    for _, r in temporal.iterrows():
        text = (
            f"- `{r['field']}`: peak {r['peak_month']}, lowest {r['low_month']}, "
            f"seasonal range {100 * r['seasonal_range_rel']:.0f}% of the mean"
        )
        n_drifting = r["n_runs_rising"] + r["n_runs_falling"]
        if n_drifting >= 0.25 * n_runs:
            text += (
                f"; changes by more than {100 * drift_flag:.0f}% of its mean over "
                f"the period in {n_drifting} runs (rising in {r['n_runs_rising']}, "
                f"falling in {r['n_runs_falling']}; median change "
                f"{100 * r['median_drift_rel']:+.0f}%), so it is not at steady state"
            )
        if r["share_months_negative"] > 0:
            text += f"; {100 * r['share_months_negative']:.0f}% of run-months negative"
        lines.append(text + ".")

    lines += ["", "In space (output_spatial_summary.csv):", ""]
    for _, r in spatial.iterrows():
        text = (
            f"- `{r['field']}`: cells {r['cell_min']:.3g} to {r['cell_max']:.3g} "
            f"{r['unit']} (median map)"
        )
        if r["rule"] == "outlet" and np.isfinite(r["outlet_over_domain_mean"]):
            where = "at a sink" if r["max_cell_is_outlet"] else "away from the sinks"
            text += (
                f"; largest {where}; sink cells average "
                f"{r['outlet_over_domain_mean']:.3g} x the mean cell"
            )
        if np.isfinite(r["spatial_cv"]) and r["spatial_cv"] < uniform_flag:
            text += f"; spatially uniform (CV {r['spatial_cv']:.2g})"
        if r["n_runs_any_negative_cell"]:
            text += f"; negative cells in {r['n_runs_any_negative_cell']} runs"
        lines.append(text + ".")
    return [*lines, ""]


def write_output_summaries(
    problem: dict, samples, data: dict, spec: dict, tables: Path, figures: Path
) -> dict[str, pd.DataFrame]:
    """Write the run, spatial and temporal summaries of the output variables."""
    responses = output_summary_by_response(data, spec)
    spatial, by_cell = output_spatial_summary(data, spec)
    temporal, climatology = output_temporal_summary(data)
    output_responses_by_run(problem, samples, data).to_csv(
        tables / "output_responses_by_run.csv", index=False
    )
    responses.to_csv(tables / "output_summary_by_response.csv", index=False)
    spatial.to_csv(tables / "output_spatial_summary.csv", index=False)
    by_cell.to_csv(tables / "output_spatial_by_cell.csv", index=False)
    temporal.to_csv(tables / "output_temporal_summary.csv", index=False)
    climatology.to_csv(tables / "output_monthly_climatology.csv", index=False)
    plot_output_overview(data, spec, figures)
    return {"responses": responses, "spatial": spatial, "temporal": temporal}


# -----------------------------------------------------------------------------
# Run the analysis
# -----------------------------------------------------------------------------


def main() -> None:
    """Run the hydrology Morris screening analysis."""
    global run_name, job_config, parameter_file, results_directory
    global replicate_directory, analysis_directory
    parser = argparse.ArgumentParser(description="Hydrology Morris analysis")
    parser.add_argument(
        "--use-cache",
        action="store_true",
        help="reuse data/responses.npz instead of reading NetCDF",
    )
    parser.add_argument("--workers", type=int, default=n_workers)
    parser.add_argument(
        "--run-name",
        help=f"run name (default {run_name}); sets the job file and the "
        "out/, out/<run>_replicates and analysis/ folders",
    )
    parser.add_argument("--results-dir", type=Path, help="out/<run> (run folders)")
    parser.add_argument("--replicate-dir", type=Path, help="out/<run>_replicates")
    parser.add_argument("--analysis-dir", type=Path, help="analysis/<run>")
    parser.add_argument(
        "--job-config", type=Path, help="job file that was run (the design)"
    )
    parser.add_argument("--parameter-file", type=Path, help="bounds used for sampling")
    args = parser.parse_args()

    if args.run_name:
        run_name = args.run_name
        job_config = module_directory / "config" / f"arrayJob_config_{run_name}.toml"
        results_directory = module_directory / "out" / run_name
        replicate_directory = module_directory / "out" / f"{run_name}_replicates"
        analysis_directory = module_directory / "analysis" / run_name
    job_config = args.job_config or job_config
    parameter_file = args.parameter_file or parameter_file
    results_directory = args.results_dir or results_directory
    replicate_directory = args.replicate_dir or replicate_directory
    analysis_directory = args.analysis_dir or analysis_directory
    print(f"Run: {run_name}\n  job file: {job_config}\n  results:  {results_directory}")
    print(f"  analysis: {analysis_directory}")

    tables, figures = analysis_directory / "tables", analysis_directory / "figures"
    for folder in (tables, figures, analysis_directory / "data"):
        folder.mkdir(parents=True, exist_ok=True)

    print("1. Design check (job-file rows form Morris trajectories on the bounds)")
    problem, samples, provenance = load_design(
        job_config,
        parameter_file,
        "morris",
        log10_parameters=None,  # read from the job-file header
        levels=None,  # read from the job-file header
        run_name=run_name,
        project_root=project_root,
    )
    levels = int(provenance["settings"]["levels"])
    design_summary, parameter_ranges = design_tables(problem, provenance)
    design_summary.to_csv(tables / "design_summary.csv", index=False)
    parameter_ranges.to_csv(tables / "parameter_ranges.csv", index=False)
    print(
        f"   D = {problem['num_vars']}, r = {provenance['settings']['trajectories']}, "
        f"p = {levels}, runs = {len(samples)}"
    )

    cache = analysis_directory / "data" / "responses.npz"
    use_cache = args.use_cache and cache.exists()
    paths, health_notes = [], []
    if not use_cache:
        print("2. Run check (parameters each run used == its design row)")
        paths = find_run_outputs(results_directory, len(samples), model_output_name)
        run_check = verify_run_parameters(paths, problem, samples)
        run_check.to_csv(tables / "run_parameter_check.csv", index=False)
        n_ok = int((run_check["status"] == "ok").sum())
        print(f"   {n_ok} of {len(paths)} runs checked and match their design row")
        if n_ok < len(paths):
            print(
                "   Note: the other runs have no compiled_configuration.toml or "
                "pbs.log, so their parameters could not be checked."
            )
        print("3. Model health (water balance, stores, vertical flow)")
        health_notes = report_model_health(
            model_health_table(paths),
            tables / "model_health_by_run.csv",
            health_tolerance,
        )

    print("4. Responses on the x/y grid")
    data = load_responses(
        paths, response_spec, cache, use_cache, project_root, args.workers
    )
    if data["scalars"].shape[0] != len(samples):
        raise ValueError("Responses do not match the design size (stale cache?).")
    save_response_spec(
        response_spec, analysis_directory / "data" / "response_spec.json"
    )
    if paths and response_spec["outlet"]["method"] == "ve_routing":
        network = ve_routing_from_output(paths[0])
        drainage_table(network).to_csv(
            analysis_directory / "data" / "drainage_network.csv", index=False
        )
        for row, col, n_cells in sorted(network["sinks"], key=lambda s: -s[2]):
            print(
                f"   sink x={network['x'][col]:.1f}, y={network['y'][row]:.1f}: "
                f"{n_cells} of {network['n_upstream'].size} cells"
            )

    print("   Output variables: run, spatial and temporal summaries")
    outputs = write_output_summaries(
        problem, samples, data, response_spec, tables, figures
    )
    health_file = tables / "model_health_by_run.csv"
    health = pd.read_csv(health_file) if health_file.exists() else None

    noise = replicate_noise(
        replicate_directory,
        provenance["replicates"],
        model_output_name,
        response_spec,
        analysis_directory / "data" / "replicate_responses.npz",
        project_root,
    )
    if noise is None:
        print("   Note: no replicate run; noise floor not assessed.")

    print("5. Morris indices")
    common = dict(num_levels=levels, conf_level=conf_level, seed=random_seed)
    scalar = scalar_morris(
        problem,
        samples,
        data,
        num_resamples=num_resamples,
        threshold=screening_threshold,
        noise=noise,
        **common,
    )
    scalar.to_csv(tables / "morris_scalar_indices.csv", index=False)
    decision = screening_decision(scalar, secondary_support)
    decision.to_csv(tables / "morris_screening_decision.csv", index=False)
    stability = ranking_stability(
        problem,
        samples,
        data,
        num_levels=levels,
        n_boot=stability_bootstraps,
        top_k=top_k,
        seed=random_seed,
    )
    stability.to_csv(tables / "morris_ranking_stability.csv", index=False)
    spatial = field_morris(
        problem, samples, data, "map", num_resamples=map_num_resamples, **common
    )
    spatial.to_csv(tables / "morris_spatial_indices.csv", index=False)
    dominant = dominant_parameter_table(spatial)
    dominant.to_csv(tables / "morris_dominant_parameter_by_cell.csv", index=False)
    monthly = field_morris(
        problem, samples, data, "series", num_resamples=map_num_resamples, **common
    )
    monthly.to_csv(tables / "morris_monthly_indices.csv", index=False)

    print("6. Figures and tables: overview, then one folder per field")
    # One colour per parameter for every figure (Sobol candidates first).
    styles = morris_parameter_styles(decision)
    plot_morris_overview(scalar, styles, figures, threshold=screening_threshold).to_csv(
        tables / "morris_mu_star_rel_by_response.csv"
    )
    response_field = {r["name"]: r["variable"] for r in response_spec["responses"]}
    response_group = {r["name"]: r["group"] for r in response_spec["responses"]}
    for field, rule in response_spec["fields"].items():
        own = [n for n in response_field if response_field[n] == field]
        group = (
            "primary"
            if any(response_group[n] == "primary" for n in own)
            else "secondary"
        )
        print(f"   {group}/{field}")
        write_field_outputs(
            field,
            group,
            own,
            rule,
            problem=problem,
            samples=samples,
            data=data,
            scalar=scalar,
            spatial=spatial,
            monthly=monthly,
            dominant=dominant,
            styles=styles,
            root=analysis_directory,
            threshold=screening_threshold,
            n_top=top_map_parameters,
        )
    summary = analysis_directory / "summary.md"
    write_morris_summary(
        summary, decision, provenance, data, noise, screening_threshold
    )
    extra = ["", "## Model health", ""]
    extra += [f"- {n}" for n in health_notes] or ["- no problems detected"]
    extra += [
        "",
        f"## Ranking stability ({stability_bootstraps} trajectory resamples)",
        "",
        f"| response | parameter | median rank | 5-95% | P(top {top_k}) |",
        "|---|---|---|---|---|",
    ]
    for _, r in stability[stability["median_rank"] <= top_k + 2].iterrows():
        extra.append(
            f"| {r['response']} | {r['parameter']} | {r['median_rank']:.0f} | "
            f"{r['rank_p05']:.0f}-{r['rank_p95']:.0f} | "
            f"{r[f'prob_top{top_k}']:.2f} |"
        )
    extra += [
        "",
        *output_findings(
            outputs["responses"],
            outputs["spatial"],
            outputs["temporal"],
            health,
            health_tolerance,
        ),
    ]
    with summary.open("a", encoding="utf-8") as handle:
        handle.write("\n".join(extra) + "\n")

    print(
        decision[
            [
                "parameter",
                "n_primary_influential",
                "n_secondary_influential",
                "max_mu_star_rel_primary",
                "sobol_candidate",
            ]
        ].to_string(index=False)
    )
    print(f"\nResults: {analysis_directory}")


if __name__ == "__main__":
    main()
