library(yaml)
library(tidyverse)
library(arrow)


# Configs ----------------------------------------------------------------

# load unit conversions
# the CSV file needs to be manually updated when there is a new unit_from and
# unit_to pairs
unit_conversions <-
  read_csv(
    "data/derived/soil/validation/config/unit_conversions.csv"
  ) |>
  # convert literal function to function objects
  mutate(
    convert_unit = map(
      `function`,
      ~ rlang::as_function(as.formula(paste("~", gsub("x", ".x", .x))))
    )
  )

# load canonical unit of VE data variables
# this YAML file is generated by tools/R/build_data_variables_table.R, which
# should be re-run once when there is any update to VE's data variable TOML
units <-
  read_yaml("data/derived/soil/validation/config/units_canonical.yaml") |>
  enframe(name = "var_canonical") |>
  unnest_wider(value) |>
  select(var_canonical, unit_to = unit)


# Ingest datasets --------------------------------------------------------

# path to source datasets
sources_dir <- "data/derived/soil/validation/config/sources"
sources_files <- list.files(
  sources_dir,
  pattern = "\\.yaml$",
  full.names = TRUE
)

# read the metadata of data sources
sources <-
  sources_files |>
  map(read_yaml) |>
  # filter and keep only sources that has the source_id entry
  keep(~ pluck_exists(.x, "source_id"))

# testing only
# source_dat <- sources[[1]]

# Harmonise each dataset
data_harmonised <-
  sources |>
  map(\(source_dat) {
    # read dataset csv file
    read_csv(
      source_dat$data_file,
      show_col_types = FALSE,
      skip = source_dat$skip_rows
    ) |>
      # select the relevant columns: unique IDs and validation variables
      select(all_of(c(source_dat$dedup_key, names(source_dat$variables)))) |>
      # combine dedup keys into a single ID column
      unite("ID", all_of(source_dat$dedup_key)) |>
      # pivot to long format because this is the easiest way to convert units and
      # remove NAs
      pivot_longer(
        cols = names(source_dat$variables),
        names_to = "var_original"
      ) |>
      filter(!is.na(value)) |>
      # join variable information, including unit and target validation variable
      left_join(
        source_dat$variables |>
          enframe(name = "var_original") |>
          unnest_wider(value),
        by = join_by(var_original)
      ) |>
      # Unit conversion
      rename(unit_from = unit) |>
      # join canonical or target units
      left_join(units, by = join_by(var_canonical)) |>
      # fallback to NA is left_join resulted in zero match
      mutate(unit_to = coalesce(unit_to, NA)) |>
      mutate(
        unit_to = ifelse(
          is.na(unit_to) & !is.na(transform),
          unit_transform,
          unit_to
        )
      ) |>
      # join conversion function
      left_join(unit_conversions, by = join_by(unit_from, unit_to)) |>
      # convert the unit finally
      mutate(value_canonical = map2(value, convert_unit, ~ .y(.x))) |>
      # add the source ID
      mutate(dataset = source_dat$source_id)
  })

# combine datasets into database
database <-
  data_harmonised |>
  list_rbind() |>
  select(
    dataset,
    ID,
    var_original,
    value_original = value,
    var_canonical,
    transform,
    unit_from,
    unit_to,
    value_canonical
  )

# Write database ---------------------------------------------------------
db_path <- "data/derived/soil/validation/database"

database |>
  group_by(dataset) |>
  write_dataset(db_path, format = "parquet")
