#' Log decision on whether a dataset should be included for validation purposes
#'
#' This function is intended to be used as \code{log_dataset()}, which will display
#' a UI in the R console and prompt you to enter the DOI and notes on
#' decisions. The log is then stored as a human-readable YAML file in the
#' specified output directory, which defaults to the soil module for now.
#'
#' @param outdir Path to the output directory, which currently defaults to the
#'   soil module
#'
#' @details
#' You will asked to enter:
#' \describe{
#'   \item{DOI}{DOI string of the dataset or publication}
#'   \item{Decision}{A menu to select decision}
#'   \item{Reason}{(Optional) A menu to select reason}
#'   \item{Notes}{(Optional) A string of long-form rationale}
#' }
#'
#' @returns A YAML file logging the decision and source metadata in
#'   \code{outdir}.
#'
#' @export
#'
#' @examples
#' box::use(tools/R/valdb)
#' box::help(valdb$log_dataset)
#' valdb$log_dataset()

log_dataset <- function(
  outdir = "data/derived/soil/validation/config/sources"
) {
  # prompt to enter DOI
  doi <- readline("Enter DOI: ")

  # download dataset metadata
  meta <- rcrossref::cr_cn(doi, format = "bibentry")

  # set up output path
  slug <- gsub("[/.]", "-", meta$doi)
  path <- file.path(outdir, paste0(slug, ".yaml"))

  # early exit if already logged
  if (file.exists(path)) {
    cli::cli_abort("A log for {doi} already exists at {path}")
  }

  # prompt for decision, decision, decision...
  decision <- utils::select.list(
    c("included", "excluded"),
    title = "Decision (enter 0 to skip): ",
    graphics = FALSE
  )
  if (decision == "") {
    decision <- "skipped"
  }

  # prompt for short-form reason
  reason <- utils::select.list(
    c("used_elsewhere", "no_raw_data", "no_soil_data"),
    title = "Reason (enter 0 to skip): ",
    graphics = FALSE
  )

  # prompt for long-form notes
  notes <- readline("Notes (leave blank to skip): ")

  # Build record
  record <- list(
    doi = meta$doi,
    decision = decision,
    reason = reason,
    notes = notes,
    logged_at = format(Sys.time(), "%Y-%m-%d"),
    metadata = list(
      title = meta$title,
      author = meta$author,
      year = meta$year,
      journal = as.character(meta$journal %||% NA),
      publisher = meta$publisher,
      url = meta$url,
      keywords = meta$keywords
    )
  )

  # Write YAML
  yaml::write_yaml(record, path)

  # Completion message
  cli::cli_alert_info("Dataset from {doi} is {decision}")
  cli::cli_alert_success("Decision log saved to\n{path}")
}


#' Title
#'
#' @param yaml_file
#'
#' @returns
#'
#' @export
#' @examples

add_schema <- function(
  config_dir = "data/derived/soil/validation/config",
  yaml_file
) {
  # Read existing YAML
  existing <- yaml::read_yaml(file.path(config_dir, yaml_file))

  # Default template schema
  template <- list(
    source_id = "author_year",
    data_file = "data/primary/soil/source_id/*.csv",
    skip_rows = 0L,
    variables = list(
      var_original_1 = list(
        var_canonical = "var_ve_1",
        transform = NA,
        unit = "unit",
        unit_transform = NA,
        description = NA
      )
    ),
    dedup_key = c("sample_id", "date", "site_id")
  )

  # Merge: existing values can override template
  merged <- purrr::list_modify(existing, !!!template)

  # Write back
  yaml::write_yaml(merged, yaml_file)

  # Open the YAML file in the editor for editing
  file.edit(yaml_file)
}


#' Title
#'
#' @param config_dir
#' @param db_path
#'
#' @returns
#'
#' @export
#' @examples

build_validation_database <- function(
  config_dir = "data/derived/soil/validation/config",
  db_path = "data/derived/soil/validation/database"
) {
  # Configs ----------------------------------------------------------------

  # load unit conversions
  # the CSV file needs to be manually updated when there is a new unit_from and
  # unit_to pairs
  unit_conversions <-
    readr::read_csv(file.path(config_dir, "unit_conversions.csv")) |>
    # convert literal function to function objects
    dplyr::mutate(
      convert_unit = purrr::map(
        `function`,
        ~ rlang::as_function(as.formula(paste("~", gsub("x", ".x", .x))))
      )
    )

  # load canonical unit of VE data variables
  # this YAML file is generated by tools/R/build_data_variables_table.R, which
  # should be re-run once when there is any update to VE's data variable TOML
  units <-
    yaml::read_yaml(file.path(config_dir, "units_canonical.yaml")) |>
    tibble::enframe(name = "var_canonical") |>
    tidyr::unnest_wider(value) |>
    dplyr::select(var_canonical, unit_to = unit)

  # Ingest datasets --------------------------------------------------------

  # path to source datasets
  sources_dir <- file.path(config_dir, "sources")
  sources_files <- list.files(
    sources_dir,
    pattern = "\\.yaml$",
    full.names = TRUE
  )

  # read the metadata of data sources
  sources <-
    sources_files |>
    purrr::map(read_yaml) |>
    # filter and keep only sources that has the source_id entry
    purrr::keep(~ purrr::pluck_exists(.x, "source_id"))

  # Harmonise each dataset
  data_harmonised <-
    sources |>
    purrr::map(\(source_dat) {
      # read dataset csv file
      readr::read_csv(
        source_dat$data_file,
        show_col_types = FALSE,
        skip = source_dat$skip_rows
      ) |>
        # select the relevant columns: unique IDs and validation variables
        dpylr::select(tidyr::all_of(c(
          source_dat$dedup_key,
          names(source_dat$variables)
        ))) |>
        # combine dedup keys into a single ID column
        tidyr::unite("ID", tidyr::all_of(source_dat$dedup_key)) |>
        # pivot to long format because this is the easiest way to convert units and
        # remove NAs
        tidyr::pivot_longer(
          cols = names(source_dat$variables),
          names_to = "var_original"
        ) |>
        dpylr::filter(!is.na(value)) |>
        # join variable information,
        # including unit and target validation variable
        dpylr::left_join(
          source_dat$variables |>
            tibble::enframe(name = "var_original") |>
            tidyr::unnest_wider(value),
          by = dpylr::join_by(var_original)
        ) |>
        # Unit conversion
        dpylr::rename(unit_from = unit) |>
        # join canonical or target units
        dpylr::left_join(units, by = dpylr::join_by(var_canonical)) |>
        # fallback to NA is left_join resulted in zero match
        dpylr::mutate(unit_to = dpylr::coalesce(unit_to, NA)) |>
        dpylr::mutate(
          unit_to = ifelse(
            is.na(unit_to) & !is.na(transform),
            unit_transform,
            unit_to
          )
        ) |>
        # join conversion function
        dpylr::left_join(
          unit_conversions,
          by = dpylr::join_by(unit_from, unit_to)
        ) |>
        # convert the unit finally
        dpylr::mutate(
          value_canonical = purrr::map2(value, convert_unit, ~ .y(.x))
        ) |>
        # add the source ID
        dpylr::mutate(dataset = source_dat$source_id)
    })

  # combine datasets into database
  database <-
    data_harmonised |>
    purrr::list_rbind() |>
    dpylr::select(
      dataset,
      ID,
      var_original,
      value_original = value,
      var_canonical,
      transform,
      unit_from,
      unit_to,
      value_canonical
    )

  # Write database ---------------------------------------------------------
  database |>
    dpylr::group_by(dataset) |>
    arrow::write_dataset(db_path, format = "parquet")
}


#' Title
#'
#' @param variables_ve
#' @param variables_derived
#'
#' @returns
#'
#' @export
#' @examples
#' box::use(tools/R/valdb)
#' valdb$build_data_variables_table()

build_data_variables_table <- function(
  variables_ve = "https://github.com/ImperialCollegeLondon/virtual_ecosystem/raw/refs/heads/develop/virtual_ecosystem/data_variables.toml",
  variables_derived = "data/derived/soil/validation/config/derived_variables.toml",
  output = "data/derived/soil/validation/config/units_canonical.yaml"
) {
  var_list <- import_variables_table(variables_ve)
  if (!is.null(variables_derived)) {
    var_list <- c(var_list, import_variables_table(variables_derived))
  }
  yaml::write_yaml(var_list, output)
}


#' Title
#'
#' @param toml
#'
#' @returns

import_variables_table <- function(toml) {
  toml::read_toml(toml) |>
    purrr::pluck("variable") |>
    {
      \(x) purrr::set_names(x, purrr::map_chr(x, "name"))
    }() |>
    purrr::map(~ purrr::discard(.x, names(.x) == "name"))
}
