name: Run pre-commit

# When does this run - new, reopened or updated PRs, pushes to main
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]


# The precommit job is not behaving - something about the caching of the precommit
# environment doesn't work on GitHub Actions, but does work on pre-commit.ci. So, this
# workflow has been disabled, but the file is retained in case we want to extend the
# actions at some point.
jobs:
  precommit:
    if: false
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: 'release'
            use-public-rspm: true
        # - uses: r-lib/actions/setup-renv@v2
        - uses: pre-commit/action@v3.0.0
